# This file is generated by scripts/codegen from
# catalog/curated_tools/longhorn_snapshots.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher longhorn_snapshot tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.longhorn import RancherLonghornSnapshotDetail, RancherLonghornSnapshotList
from rancher_mcp.models.resources import RancherMutationReceipt
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.longhorn.paths import (
    longhorn_namespaced_collection_path,
    longhorn_namespaced_resource_path,
)
from rancher_mcp.tools.longhorn.shared import (
    build_list_query_params,
    items,
    snapshot_summary_from_payload,
)
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_longhorn_snapshots_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    volume: str | None,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherLonghornSnapshotList:
    """Fetch and normalize longhorn_snapshots through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        longhorn_namespaced_collection_path(cluster_id, namespace, "snapshots"),
        params=query_params or None,
    )
    longhorn_snapshots = [snapshot_summary_from_payload(item) for item in items(payload)]
    if volume is not None:
        longhorn_snapshots = [
            longhorn_snapshot
            for longhorn_snapshot in longhorn_snapshots
            if longhorn_snapshot.volume == volume
        ]
    return RancherLonghornSnapshotList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        snapshot_count=len(longhorn_snapshots),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        snapshots=longhorn_snapshots,
        suggested_next_steps=[
            "rancher_longhorn_snapshot_get",
            "rancher_longhorn_volumes_list",
        ],
    )


async def rancher_longhorn_snapshots_list(
    namespace: str,
    cluster_id: str = "local",
    volume: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLonghornSnapshotList:
    """List longhorn_snapshots in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_longhorn_snapshots_list(
            instance_name,
            cluster_id,
            namespace,
            volume,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_longhorn_snapshots_list(
            instance_name,
            cluster_id,
            namespace,
            volume,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_longhorn_snapshot_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    snapshot_name: str,
    client: ManagementDiscoveryClient,
) -> RancherLonghornSnapshotDetail:
    """Fetch and normalize one longhorn_snapshot."""

    payload = await client.get_json(
        longhorn_namespaced_resource_path(cluster_id, namespace, "snapshots", snapshot_name)
    )

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherLonghornSnapshotDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_longhorn_snapshots_list",
                "rancher_longhorn_volumes_list",
            ],
        }
    )


async def rancher_longhorn_snapshot_get(
    namespace: str,
    snapshot_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLonghornSnapshotDetail:
    """Fetch one longhorn_snapshot by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_longhorn_snapshot_get(
            instance_name, cluster_id, namespace, snapshot_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_longhorn_snapshot_get(
            instance_name,
            cluster_id,
            namespace,
            snapshot_name,
            managed_client,
        )


async def _patch_longhorn_snapshot_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    snapshot_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_labels one longhorn_snapshot via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            longhorn_namespaced_resource_path(cluster_id, namespace, "snapshots", snapshot_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="longhorn_snapshot",
        action="set_labels",
        name=snapshot_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        longhorn_namespaced_resource_path(cluster_id, namespace, "snapshots", snapshot_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="longhorn_snapshot",
        name=snapshot_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="longhorn_snapshot_set_labels", plane="steve")
@rate_limit_writes
async def rancher_longhorn_snapshot_set_labels(
    namespace: str,
    snapshot_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one longhorn_snapshot via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_longhorn_snapshot_set_labels(
            instance_name,
            cluster_id,
            namespace,
            snapshot_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_longhorn_snapshot_set_labels(
            instance_name,
            cluster_id,
            namespace,
            snapshot_name,
            labels,
            managed_client,
        )


async def _patch_longhorn_snapshot_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    snapshot_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_annotations one longhorn_snapshot via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            longhorn_namespaced_resource_path(cluster_id, namespace, "snapshots", snapshot_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="longhorn_snapshot",
        action="set_annotations",
        name=snapshot_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        longhorn_namespaced_resource_path(cluster_id, namespace, "snapshots", snapshot_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="longhorn_snapshot",
        name=snapshot_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="longhorn_snapshot_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_longhorn_snapshot_set_annotations(
    namespace: str,
    snapshot_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one longhorn_snapshot via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_longhorn_snapshot_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            snapshot_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_longhorn_snapshot_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            snapshot_name,
            annotations,
            managed_client,
        )


async def rancher_longhorn_snapshots_list_tool(
    namespace: str,
    cluster_id: str = "local",
    volume: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherLonghornSnapshotList:
    """Public MCP wrapper for curated longhorn_snapshot list."""

    return await rancher_longhorn_snapshots_list(
        namespace=namespace,
        cluster_id=cluster_id,
        volume=volume,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_longhorn_snapshot_get_tool(
    namespace: str,
    snapshot_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherLonghornSnapshotDetail:
    """Public MCP wrapper for curated longhorn_snapshot detail."""

    return await rancher_longhorn_snapshot_get(
        namespace=namespace,
        snapshot_name=snapshot_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_longhorn_snapshot_set_labels_tool(
    namespace: str,
    snapshot_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Public MCP wrapper for curated longhorn_snapshot set_labels."""

    return await rancher_longhorn_snapshot_set_labels(
        namespace=namespace,
        snapshot_name=snapshot_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_longhorn_snapshot_set_annotations_tool(
    namespace: str,
    snapshot_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Public MCP wrapper for curated longhorn_snapshot set_annotations."""

    return await rancher_longhorn_snapshot_set_annotations(
        namespace=namespace,
        snapshot_name=snapshot_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
