# This file is generated by scripts/codegen from
# catalog/curated_tools/_packs/logging_backups.yml plus all per-resource
# descriptors in the same pack. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher logging and backup tool facade."""

from mcp.server.fastmcp import FastMCP

from rancher_mcp.tools.logging_backups._generated_cluster_loggings import (
    rancher_cluster_logging_get,
    rancher_cluster_logging_get_tool,
    rancher_cluster_loggings_list,
    rancher_cluster_loggings_list_tool,
)
from rancher_mcp.tools.logging_backups._generated_etcd_backups import (
    rancher_etcd_backup_get,
    rancher_etcd_backup_get_tool,
    rancher_etcd_backups_list,
    rancher_etcd_backups_list_tool,
)
from rancher_mcp.tools.logging_backups._generated_project_loggings import (
    rancher_project_logging_get,
    rancher_project_logging_get_tool,
    rancher_project_loggings_list,
    rancher_project_loggings_list_tool,
)
from rancher_mcp.tools.support.annotations import READ_ONLY

__all__ = [
    "rancher_cluster_logging_get",
    "rancher_cluster_loggings_list",
    "rancher_etcd_backup_get",
    "rancher_etcd_backups_list",
    "rancher_project_logging_get",
    "rancher_project_loggings_list",
    "register_logging_backup_tools",
]


def register_logging_backup_tools(mcp: FastMCP) -> None:
    """Register curated logging and backup tools with the FastMCP server."""

    mcp.tool(name="rancher_cluster_loggings_list", annotations=READ_ONLY)(
        rancher_cluster_loggings_list_tool
    )
    mcp.tool(name="rancher_cluster_logging_get", annotations=READ_ONLY)(
        rancher_cluster_logging_get_tool
    )
    mcp.tool(name="rancher_etcd_backups_list", annotations=READ_ONLY)(
        rancher_etcd_backups_list_tool
    )
    mcp.tool(name="rancher_etcd_backup_get", annotations=READ_ONLY)(rancher_etcd_backup_get_tool)
    mcp.tool(name="rancher_project_loggings_list", annotations=READ_ONLY)(
        rancher_project_loggings_list_tool
    )
    mcp.tool(name="rancher_project_logging_get", annotations=READ_ONLY)(
        rancher_project_logging_get_tool
    )
