# This file is generated by scripts/codegen from
# catalog/curated_tools/cis_scan_profiles.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cis_scan_profile tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.compliance import RancherCisScanProfileDetail, RancherCisScanProfileList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.compliance.shared import (
    build_cis_scan_profile_query_params,
    cis_scan_profile_summary_from_payload,
    data_items,
    tests_from_payload,
)


async def _fetch_cis_scan_profiles_list(
    instance_name: str,
    limit: int | None,
    cluster_id: str | None,
    client: ManagementDiscoveryClient,
) -> RancherCisScanProfileList:
    """Fetch and normalize the Rancher cis_scan_profiles collection."""

    query_params = build_cis_scan_profile_query_params(
        limit=limit,
        cluster_id=cluster_id,
    )
    payload = await client.get_json("/v3/cisscanprofiles", params=query_params or None)
    cis_scan_profiles = [
        cis_scan_profile_summary_from_payload(item) for item in data_items(payload)
    ]
    return RancherCisScanProfileList(
        instance=instance_name,
        profile_count=len(cis_scan_profiles),
        applied_query_params=query_params,
        profiles=cis_scan_profiles,
        suggested_next_steps=[
            "rancher_cis_scan_profile_get",
            "rancher_cis_scans_list",
        ],
    )


async def rancher_cis_scan_profiles_list(
    limit: int | None = None,
    cluster_id: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCisScanProfileList:
    """List cis_scan_profiles with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cis_scan_profiles_list(
            instance_name,
            limit,
            cluster_id,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cis_scan_profiles_list(
            instance_name,
            limit,
            cluster_id,
            managed_client,
        )


async def _fetch_cis_scan_profile_get(
    instance_name: str,
    profile_id: str,
    client: ManagementDiscoveryClient,
) -> RancherCisScanProfileDetail:
    """Fetch and normalize one cis_scan_profile."""

    payload = await client.get_json(f"/v3/cisscanprofiles/{profile_id}")

    detail = RancherCisScanProfileDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "tests": tests_from_payload(payload),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_cis_scan_profiles_list", "rancher_cis_scans_list"],
        }
    )


async def rancher_cis_scan_profile_get(
    profile_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCisScanProfileDetail:
    """Fetch one cis_scan_profile by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cis_scan_profile_get(instance_name, profile_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cis_scan_profile_get(
            instance_name,
            profile_id,
            managed_client,
        )


async def rancher_cis_scan_profiles_list_tool(
    limit: int | None = None,
    cluster_id: str | None = None,
    instance: str | None = None,
) -> RancherCisScanProfileList:
    """List cis_scan_profiles as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_cis_scan_profiles_list(
        limit=limit,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cis_scan_profile_get_tool(
    profile_id: str,
    instance: str | None = None,
) -> RancherCisScanProfileDetail:
    """Fetch one cis_scan_profile and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_cis_scan_profile_get(
        profile_id=profile_id,
        instance=instance,
    )
