# This file is generated by scripts/codegen from
# catalog/curated_tools/certificates.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher certificate tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.certificates import RancherCertificateDetail, RancherCertificateList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.certificates.shared import (
    build_certificate_query_params,
    certificate_summary_from_payload,
    data_items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_certificates_list(
    instance_name: str,
    limit: int | None,
    name: str | None,
    state: str | None,
    project_id: str | None,
    sort_by: str | None,
    reverse: bool | None,
    client: ManagementDiscoveryClient,
) -> RancherCertificateList:
    """Fetch and normalize the Rancher certificates collection."""

    query_params = build_certificate_query_params(
        limit=limit,
        name=name,
        state=state,
        project_id=project_id,
        sort_by=sort_by,
        reverse=reverse,
    )
    payload = await client.get_json("/v3/certificates", params=query_params or None)
    certificates = [certificate_summary_from_payload(item) for item in data_items(payload)]
    return RancherCertificateList(
        instance=instance_name,
        certificate_count=len(certificates),
        applied_query_params=query_params,
        certificates=certificates,
        suggested_next_steps=[
            "rancher_certificate_get",
            "rancher_namespaced_certificates_list",
        ],
    )


async def rancher_certificates_list(
    limit: int | None = None,
    name: str | None = None,
    state: str | None = None,
    project_id: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertificateList:
    """List certificates with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_certificates_list(
            instance_name,
            limit,
            name,
            state,
            project_id,
            sort_by,
            reverse,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_certificates_list(
            instance_name,
            limit,
            name,
            state,
            project_id,
            sort_by,
            reverse,
            managed_client,
        )


async def _fetch_certificate_get(
    instance_name: str,
    certificate_id: str,
    client: ManagementDiscoveryClient,
) -> RancherCertificateDetail:
    """Fetch and normalize one certificate."""

    payload = await client.get_json(f"/v3/certificates/{certificate_id}")

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherCertificateDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "annotation_keys": sorted(string_dict(annotations)),
            "action_keys": sorted(mapping_value(payload, "actions") or {}),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "suggested_next_steps": ["rancher_certificates_list", "rancher_norman_resource_get"],
        }
    )


async def rancher_certificate_get(
    certificate_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertificateDetail:
    """Fetch one certificate by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_certificate_get(instance_name, certificate_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_certificate_get(
            instance_name,
            certificate_id,
            managed_client,
        )


async def rancher_certificates_list_tool(
    limit: int | None = None,
    name: str | None = None,
    state: str | None = None,
    project_id: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
) -> RancherCertificateList:
    """List certificates as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_certificates_list(
        limit=limit,
        name=name,
        state=state,
        project_id=project_id,
        sort_by=sort_by,
        reverse=reverse,
        instance=instance,
    )


async def rancher_certificate_get_tool(
    certificate_id: str,
    instance: str | None = None,
) -> RancherCertificateDetail:
    """Fetch one certificate and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_certificate_get(
        certificate_id=certificate_id,
        instance=instance,
    )
