# This file is generated by scripts/codegen from
# catalog/curated_tools/cluster_policy_reports.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cluster_policy_report tools."""

from __future__ import annotations

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.policy_reports import (
    RancherClusterPolicyReportDetail,
    RancherClusterPolicyReportList,
)
from rancher_mcp.models.resources import RancherCuratedDeleteResult
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.policy_reports.paths import (
    policy_cluster_collection_path,
    policy_cluster_resource_path,
)
from rancher_mcp.tools.policy_reports.shared import (
    build_list_query_params,
    cluster_policy_report_summary_from_payload,
    items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_cluster_policy_reports_list(
    instance_name: str,
    cluster_id: str,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherClusterPolicyReportList:
    """Fetch and normalize cluster_policy_reports through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        policy_cluster_collection_path(cluster_id, "clusterpolicyreports"),
        params=query_params or None,
    )
    cluster_policy_reports = [
        cluster_policy_report_summary_from_payload(item) for item in items(payload)
    ]
    return RancherClusterPolicyReportList(
        instance=instance_name,
        cluster_id=cluster_id,
        cluster_policy_report_count=len(cluster_policy_reports),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        cluster_policy_reports=cluster_policy_reports,
        suggested_next_steps=[
            "rancher_cluster_policy_report_get",
            "rancher_policy_reports_list",
        ],
    )


async def rancher_cluster_policy_reports_list(
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherClusterPolicyReportList:
    """List cluster_policy_reports with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_policy_reports_list(
            instance_name,
            cluster_id,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_policy_reports_list(
            instance_name,
            cluster_id,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_cluster_policy_report_get(
    instance_name: str,
    cluster_id: str,
    report_name: str,
    client: ManagementDiscoveryClient,
) -> RancherClusterPolicyReportDetail:
    """Fetch and normalize one cluster_policy_report."""

    payload = await client.get_json(
        policy_cluster_resource_path(cluster_id, "clusterpolicyreports", report_name)
    )
    summary = cluster_policy_report_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherClusterPolicyReportDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "result_count": summary.result_count,
            "top_failing_policies": summary.top_failing_policies,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_cluster_policy_reports_list",
                "rancher_policy_reports_list",
            ],
        }
    )


async def rancher_cluster_policy_report_get(
    report_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherClusterPolicyReportDetail:
    """Fetch one cluster_policy_report by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_policy_report_get(
            instance_name, cluster_id, report_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_policy_report_get(
            instance_name,
            cluster_id,
            report_name,
            managed_client,
        )


async def _delete_cluster_policy_report(
    instance_name: str,
    cluster_id: str,
    report_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one cluster_policy_report; returns a typed delete result."""

    response_payload = await client.delete_json(
        policy_cluster_resource_path(cluster_id, "clusterpolicyreports", report_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="cluster_policy_report",
        resource_name=report_name,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_cluster_policy_reports_list"],
    )


@audit_mutation(operation="cluster_policy_report_delete", plane="steve")
@rate_limit_writes
async def rancher_cluster_policy_report_delete(
    report_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one cluster_policy_report after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete cluster_policy_report {report_name}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_cluster_policy_report(
            instance_name,
            cluster_id,
            report_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_cluster_policy_report(
            instance_name,
            cluster_id,
            report_name,
            expected_phrase,
            managed_client,
        )


async def _patch_cluster_policy_report_set_labels(
    instance_name: str,
    cluster_id: str,
    report_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherClusterPolicyReportDetail:
    """Set_labels one cluster_policy_report via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    payload = await client.patch_json(
        policy_cluster_resource_path(cluster_id, "clusterpolicyreports", report_name),
        payload=request_payload,
    )
    summary = cluster_policy_report_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherClusterPolicyReportDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "result_count": summary.result_count,
            "top_failing_policies": summary.top_failing_policies,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_cluster_policy_report_get"],
        }
    )


@audit_mutation(operation="cluster_policy_report_set_labels", plane="steve")
@rate_limit_writes
async def rancher_cluster_policy_report_set_labels(
    report_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherClusterPolicyReportDetail:
    """Set_labels one cluster_policy_report via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_cluster_policy_report_set_labels(
            instance_name,
            cluster_id,
            report_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_cluster_policy_report_set_labels(
            instance_name,
            cluster_id,
            report_name,
            labels,
            managed_client,
        )


async def _patch_cluster_policy_report_set_annotations(
    instance_name: str,
    cluster_id: str,
    report_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherClusterPolicyReportDetail:
    """Set_annotations one cluster_policy_report via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    payload = await client.patch_json(
        policy_cluster_resource_path(cluster_id, "clusterpolicyreports", report_name),
        payload=request_payload,
    )
    summary = cluster_policy_report_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherClusterPolicyReportDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "result_count": summary.result_count,
            "top_failing_policies": summary.top_failing_policies,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_cluster_policy_report_get"],
        }
    )


@audit_mutation(operation="cluster_policy_report_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_cluster_policy_report_set_annotations(
    report_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherClusterPolicyReportDetail:
    """Set_annotations one cluster_policy_report via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_cluster_policy_report_set_annotations(
            instance_name,
            cluster_id,
            report_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_cluster_policy_report_set_annotations(
            instance_name,
            cluster_id,
            report_name,
            annotations,
            managed_client,
        )


async def rancher_cluster_policy_reports_list_tool(
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherClusterPolicyReportList:
    """Public MCP wrapper for curated cluster_policy_report list."""

    return await rancher_cluster_policy_reports_list(
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_cluster_policy_report_get_tool(
    report_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherClusterPolicyReportDetail:
    """Public MCP wrapper for curated cluster_policy_report detail."""

    return await rancher_cluster_policy_report_get(
        report_name=report_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cluster_policy_report_delete_tool(
    report_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Public MCP wrapper for curated cluster_policy_report delete."""

    return await rancher_cluster_policy_report_delete(
        report_name=report_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cluster_policy_report_set_labels_tool(
    report_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherClusterPolicyReportDetail:
    """Public MCP wrapper for curated cluster_policy_report set_labels."""

    return await rancher_cluster_policy_report_set_labels(
        report_name=report_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cluster_policy_report_set_annotations_tool(
    report_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherClusterPolicyReportDetail:
    """Public MCP wrapper for curated cluster_policy_report set_annotations."""

    return await rancher_cluster_policy_report_set_annotations(
        report_name=report_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
