# This file is generated by scripts/codegen from
# catalog/curated_tools/namespaces.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher namespace tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.steve import RancherSteveClient, SteveMutationClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.projects_namespaces import RancherNamespaceDetail, RancherNamespaceList
from rancher_mcp.models.resources import RancherMutationReceipt
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.projects_namespaces.shared import (
    build_namespace_query_params,
    data_items,
    namespace_cattle_conditions,
    namespace_cluster_id,
    namespace_summary_from_payload,
    string_dict,
)
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value


async def _fetch_namespaces_list(
    instance_name: str,
    cluster_id: str,
    phase: str | None,
    project_id: str | None,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: SteveMutationClient,
    page_token: str | None = None,
) -> RancherNamespaceList:
    """Fetch and normalize the namespaces collection."""

    query_params = build_namespace_query_params(
        project_id=project_id,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        continue_token=page_token,
    )
    payload = await client.get_json("/namespaces", params=query_params or None)
    namespaces = [namespace_summary_from_payload(item) for item in data_items(payload)]
    namespaces = [
        namespace.model_copy(
            update={
                "cluster_id": namespace_cluster_id(namespace, cluster_id),
            }
        )
        for namespace in namespaces
    ]
    if phase is not None:
        namespaces = [namespace for namespace in namespaces if namespace.phase == phase]
    return RancherNamespaceList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace_count=len(namespaces),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        namespaces=namespaces,
        suggested_next_steps=[
            "rancher_namespace_get",
            "rancher_pods_list",
            "rancher_deployments_list",
        ],
    )


async def rancher_namespaces_list(
    cluster_id: str = "local",
    phase: str | None = None,
    project_id: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherNamespaceList:
    """List namespaces with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_namespaces_list(
            instance_name,
            cluster_id,
            phase,
            project_id,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _fetch_namespaces_list(
            instance_name,
            cluster_id,
            phase,
            project_id,
            limit,
            label_selector,
            field_selector,
            steve_client,
            page_token,
        )


async def _fetch_namespace_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    client: SteveMutationClient,
) -> RancherNamespaceDetail:
    """Fetch and normalize one namespace."""

    payload = await client.get_json(f"/namespaces/{namespace}")
    summary = namespace_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    metadata_labels = mapping_value(metadata, "labels") or {}
    detail = RancherNamespaceDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "id": summary.id,
            "finalizer_count": summary.finalizer_count,
            "cluster_id": namespace_cluster_id(summary, cluster_id),
            "label_keys": sorted(string_dict(metadata_labels)),
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "cattle_conditions": namespace_cattle_conditions(metadata),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_namespaces_list",
                "rancher_pods_list",
                "rancher_deployments_list",
            ],
        }
    )


async def rancher_namespace_get(
    namespace: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherNamespaceDetail:
    """Fetch one namespace by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_namespace_get(instance_name, cluster_id, namespace, client)
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _fetch_namespace_get(
            instance_name,
            cluster_id,
            namespace,
            steve_client,
        )


async def _patch_namespace_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    labels: dict[str, str],
    client: SteveMutationClient,
) -> RancherMutationReceipt:
    """Set_labels one namespace via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(f"/namespaces/{namespace}"),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="namespace",
        action="set_labels",
        name=namespace,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(f"/namespaces/{namespace}", payload=request_payload)
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="namespace",
        name=namespace,
        cluster_id=cluster_id,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="namespace_set_labels", plane="steve")
@rate_limit_writes
async def rancher_namespace_set_labels(
    namespace: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one namespace via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_namespace_set_labels(
            instance_name,
            cluster_id,
            namespace,
            labels,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _patch_namespace_set_labels(
            instance_name,
            cluster_id,
            namespace,
            labels,
            steve_client,
        )


async def _patch_namespace_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    annotations: dict[str, str],
    client: SteveMutationClient,
) -> RancherMutationReceipt:
    """Set_annotations one namespace via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(f"/namespaces/{namespace}"),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="namespace",
        action="set_annotations",
        name=namespace,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(f"/namespaces/{namespace}", payload=request_payload)
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="namespace",
        name=namespace,
        cluster_id=cluster_id,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="namespace_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_namespace_set_annotations(
    namespace: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one namespace via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_namespace_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            annotations,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _patch_namespace_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            annotations,
            steve_client,
        )


async def rancher_namespaces_list_tool(
    cluster_id: str = "local",
    phase: str | None = None,
    project_id: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherNamespaceList:
    """Public MCP wrapper for curated namespace list."""

    return await rancher_namespaces_list(
        cluster_id=cluster_id,
        phase=phase,
        project_id=project_id,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_namespace_get_tool(
    namespace: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherNamespaceDetail:
    """Public MCP wrapper for curated namespace detail."""

    return await rancher_namespace_get(
        namespace=namespace,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_namespace_set_labels_tool(
    namespace: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Public MCP wrapper for curated namespace set_labels."""

    return await rancher_namespace_set_labels(
        namespace=namespace,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_namespace_set_annotations_tool(
    namespace: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Public MCP wrapper for curated namespace set_annotations."""

    return await rancher_namespace_set_annotations(
        namespace=namespace,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
