# This file is generated by scripts/codegen from
# catalog/curated_tools/fleet_workspaces.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher fleet_workspace tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.fleet_registration import (
    RancherFleetWorkspaceDetail,
    RancherFleetWorkspaceList,
)
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.fleet_registration.shared import (
    action_keys,
    build_fleet_workspace_query_params,
    data_items,
    fleet_workspace_summary_from_payload,
    link_keys,
    status_keys,
)


async def _fetch_fleet_workspaces_list(
    instance_name: str,
    limit: int | None,
    name: str | None,
    sort_by: str | None,
    reverse: bool | None,
    client: ManagementDiscoveryClient,
) -> RancherFleetWorkspaceList:
    """Fetch and normalize the Rancher fleet_workspaces collection."""

    query_params = build_fleet_workspace_query_params(
        limit=limit,
        name=name,
        sort_by=sort_by,
        reverse=reverse,
    )
    payload = await client.get_json("/v3/fleetworkspaces", params=query_params or None)
    fleet_workspaces = [fleet_workspace_summary_from_payload(item) for item in data_items(payload)]
    return RancherFleetWorkspaceList(
        instance=instance_name,
        fleet_workspace_count=len(fleet_workspaces),
        applied_query_params=query_params,
        fleet_workspaces=fleet_workspaces,
        suggested_next_steps=[
            "rancher_fleet_workspace_get",
            "rancher_cluster_registration_tokens_list",
        ],
    )


async def rancher_fleet_workspaces_list(
    limit: int | None = None,
    name: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherFleetWorkspaceList:
    """List fleet_workspaces with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_fleet_workspaces_list(
            instance_name,
            limit,
            name,
            sort_by,
            reverse,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_fleet_workspaces_list(
            instance_name,
            limit,
            name,
            sort_by,
            reverse,
            managed_client,
        )


async def _fetch_fleet_workspace_get(
    instance_name: str,
    fleet_workspace_id: str,
    client: ManagementDiscoveryClient,
) -> RancherFleetWorkspaceDetail:
    """Fetch and normalize one fleet_workspace."""

    payload = await client.get_json(f"/v3/fleetworkspaces/{fleet_workspace_id}")

    detail = RancherFleetWorkspaceDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "status_keys": status_keys(payload),
            "action_keys": action_keys(payload),
            "link_keys": link_keys(payload),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_fleet_workspaces_list",
                "rancher_cluster_registration_tokens_list",
            ],
        }
    )


async def rancher_fleet_workspace_get(
    fleet_workspace_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherFleetWorkspaceDetail:
    """Fetch one fleet_workspace by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_fleet_workspace_get(instance_name, fleet_workspace_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_fleet_workspace_get(
            instance_name,
            fleet_workspace_id,
            managed_client,
        )


async def rancher_fleet_workspaces_list_tool(
    limit: int | None = None,
    name: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
) -> RancherFleetWorkspaceList:
    """List fleet_workspaces as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_fleet_workspaces_list(
        limit=limit,
        name=name,
        sort_by=sort_by,
        reverse=reverse,
        instance=instance,
    )


async def rancher_fleet_workspace_get_tool(
    fleet_workspace_id: str,
    instance: str | None = None,
) -> RancherFleetWorkspaceDetail:
    """Fetch one fleet_workspace and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_fleet_workspace_get(
        fleet_workspace_id=fleet_workspace_id,
        instance=instance,
    )
