# This file is generated by scripts/codegen from
# catalog/curated_tools/users.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher user tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.auth_identity import RancherUserDetail, RancherUserList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.auth_identity.shared import (
    build_user_query_params,
    condition_types_true_sorted,
    data_items,
    user_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value


async def _fetch_users_list(
    instance_name: str,
    limit: int | None,
    state: str | None,
    enabled: bool | None,
    me: bool | None,
    sort_by: str | None,
    reverse: bool | None,
    client: ManagementDiscoveryClient,
) -> RancherUserList:
    """Fetch and normalize the Rancher users collection."""

    query_params = build_user_query_params(
        limit=limit,
        state=state,
        enabled=enabled,
        me=me,
        sort_by=sort_by,
        reverse=reverse,
    )
    payload = await client.get_json("/v3/users", params=query_params or None)
    users = [user_summary_from_payload(item) for item in data_items(payload)]
    return RancherUserList(
        instance=instance_name,
        user_count=len(users),
        applied_query_params=query_params,
        users=users,
        suggested_next_steps=[
            "rancher_user_get",
            "rancher_groups_list",
        ],
    )


async def rancher_users_list(
    limit: int | None = None,
    state: str | None = None,
    enabled: bool | None = None,
    me: bool | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherUserList:
    """List users with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_users_list(
            instance_name,
            limit,
            state,
            enabled,
            me,
            sort_by,
            reverse,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_users_list(
            instance_name,
            limit,
            state,
            enabled,
            me,
            sort_by,
            reverse,
            managed_client,
        )


async def _fetch_user_get(
    instance_name: str,
    user_id: str,
    client: ManagementDiscoveryClient,
) -> RancherUserDetail:
    """Fetch and normalize one user."""

    payload = await client.get_json(f"/v3/users/{user_id}")

    detail = RancherUserDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "condition_types_true": condition_types_true_sorted(detail.conditions),
            "action_keys": sorted(mapping_value(payload, "actions") or {}),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_users_list", "rancher_groups_list"],
        }
    )


async def rancher_user_get(
    user_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherUserDetail:
    """Fetch one user by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_user_get(instance_name, user_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_user_get(
            instance_name,
            user_id,
            managed_client,
        )


async def rancher_users_list_tool(
    limit: int | None = None,
    state: str | None = None,
    enabled: bool | None = None,
    me: bool | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
) -> RancherUserList:
    """List users as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_users_list(
        limit=limit,
        state=state,
        enabled=enabled,
        me=me,
        sort_by=sort_by,
        reverse=reverse,
        instance=instance,
    )


async def rancher_user_get_tool(
    user_id: str,
    instance: str | None = None,
) -> RancherUserDetail:
    """Fetch one user and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_user_get(
        user_id=user_id,
        instance=instance,
    )
