# This file is generated by scripts/codegen from
# catalog/curated_tools/endpoint_slices.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher endpoint_slice tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.networking import RancherEndpointSliceDetail, RancherEndpointSliceList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.networking.paths import (
    discovery_v1_collection_path,
    discovery_v1_resource_path,
)
from rancher_mcp.tools.networking.shared import (
    build_list_query_params,
    endpoint_slice_summary_from_payload,
    items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_endpoint_slices_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    target_service: str | None,
    address_type: str | None,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherEndpointSliceList:
    """Fetch and normalize endpoint_slices through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        discovery_v1_collection_path(cluster_id, namespace, "endpointslices"),
        params=query_params or None,
    )
    endpoint_slices = [endpoint_slice_summary_from_payload(item) for item in items(payload)]
    if target_service is not None:
        endpoint_slices = [
            endpoint_slice
            for endpoint_slice in endpoint_slices
            if endpoint_slice.target_service == target_service
        ]
    if address_type is not None:
        endpoint_slices = [
            endpoint_slice
            for endpoint_slice in endpoint_slices
            if endpoint_slice.address_type == address_type
        ]
    return RancherEndpointSliceList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        endpoint_slice_count=len(endpoint_slices),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        endpoint_slices=endpoint_slices,
        suggested_next_steps=[
            "rancher_endpoint_slice_get",
            "rancher_services_list",
            "rancher_pods_list",
        ],
    )


async def rancher_endpoint_slices_list(
    namespace: str,
    cluster_id: str = "local",
    target_service: str | None = None,
    address_type: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherEndpointSliceList:
    """List endpoint_slices in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_endpoint_slices_list(
            instance_name,
            cluster_id,
            namespace,
            target_service,
            address_type,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_endpoint_slices_list(
            instance_name,
            cluster_id,
            namespace,
            target_service,
            address_type,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_endpoint_slice_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    endpoint_slice_name: str,
    client: ManagementDiscoveryClient,
) -> RancherEndpointSliceDetail:
    """Fetch and normalize one endpoint_slice."""

    payload = await client.get_json(
        discovery_v1_resource_path(cluster_id, namespace, "endpointslices", endpoint_slice_name)
    )
    summary = endpoint_slice_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherEndpointSliceDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "port_count": summary.port_count,
            "endpoint_count": summary.endpoint_count,
            "ready_endpoint_count": summary.ready_endpoint_count,
            "annotation_keys": sorted(string_dict(annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_endpoint_slices_list", "rancher_services_list"],
        }
    )


async def rancher_endpoint_slice_get(
    namespace: str,
    endpoint_slice_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherEndpointSliceDetail:
    """Fetch one endpoint_slice by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_endpoint_slice_get(
            instance_name, cluster_id, namespace, endpoint_slice_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_endpoint_slice_get(
            instance_name,
            cluster_id,
            namespace,
            endpoint_slice_name,
            managed_client,
        )


async def rancher_endpoint_slices_list_tool(
    namespace: str,
    cluster_id: str = "local",
    target_service: str | None = None,
    address_type: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherEndpointSliceList:
    """Public MCP wrapper for curated endpoint_slice list."""

    return await rancher_endpoint_slices_list(
        namespace=namespace,
        cluster_id=cluster_id,
        target_service=target_service,
        address_type=address_type,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_endpoint_slice_get_tool(
    namespace: str,
    endpoint_slice_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherEndpointSliceDetail:
    """Public MCP wrapper for curated endpoint_slice detail."""

    return await rancher_endpoint_slice_get(
        namespace=namespace,
        endpoint_slice_name=endpoint_slice_name,
        cluster_id=cluster_id,
        instance=instance,
    )
