# This file is generated by scripts/codegen from
# catalog/curated_tools/network_policies.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher network_policy tools."""

from __future__ import annotations

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.networking import RancherNetworkPolicyDetail, RancherNetworkPolicyList
from rancher_mcp.models.resources import RancherCuratedDeleteResult
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.networking.paths import (
    networking_v1_collection_path,
    networking_v1_resource_path,
)
from rancher_mcp.tools.networking.shared import (
    build_list_query_params,
    items,
    network_policy_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_network_policies_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherNetworkPolicyList:
    """Fetch and normalize network_policies through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        networking_v1_collection_path(cluster_id, namespace, "networkpolicies"),
        params=query_params or None,
    )
    network_policies = [network_policy_summary_from_payload(item) for item in items(payload)]
    return RancherNetworkPolicyList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        network_policy_count=len(network_policies),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        network_policies=network_policies,
        suggested_next_steps=[
            "rancher_network_policy_get",
            "rancher_pods_list",
        ],
    )


async def rancher_network_policies_list(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNetworkPolicyList:
    """List network_policies in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_network_policies_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_network_policies_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_network_policy_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    network_policy_name: str,
    client: ManagementDiscoveryClient,
) -> RancherNetworkPolicyDetail:
    """Fetch and normalize one network_policy."""

    payload = await client.get_json(
        networking_v1_resource_path(cluster_id, namespace, "networkpolicies", network_policy_name)
    )
    summary = network_policy_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherNetworkPolicyDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ingress_rule_count": summary.ingress_rule_count,
            "egress_rule_count": summary.egress_rule_count,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_network_policies_list", "rancher_pods_list"],
        }
    )


async def rancher_network_policy_get(
    namespace: str,
    network_policy_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNetworkPolicyDetail:
    """Fetch one network_policy by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_network_policy_get(
            instance_name, cluster_id, namespace, network_policy_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_network_policy_get(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            managed_client,
        )


async def _delete_network_policy(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    network_policy_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one network_policy; returns a typed delete result."""

    response_payload = await client.delete_json(
        networking_v1_resource_path(cluster_id, namespace, "networkpolicies", network_policy_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="network_policy",
        resource_name=network_policy_name,
        namespace=namespace,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_network_policies_list"],
    )


@audit_mutation(operation="network_policy_delete", plane="steve")
@rate_limit_writes
async def rancher_network_policy_delete(
    namespace: str,
    network_policy_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one network_policy after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete network_policy {network_policy_name} in namespace {namespace}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_network_policy(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_network_policy(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            expected_phrase,
            managed_client,
        )


async def _patch_network_policy_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    network_policy_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherNetworkPolicyDetail:
    """Set_labels one network_policy via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = {"metadata": patch_subtree}
    payload = await client.patch_json(
        networking_v1_resource_path(cluster_id, namespace, "networkpolicies", network_policy_name),
        payload=request_payload,
    )
    summary = network_policy_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherNetworkPolicyDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ingress_rule_count": summary.ingress_rule_count,
            "egress_rule_count": summary.egress_rule_count,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_network_policy_get", "rancher_network_policies_list"],
        }
    )


@audit_mutation(operation="network_policy_set_labels", plane="steve")
@rate_limit_writes
async def rancher_network_policy_set_labels(
    namespace: str,
    network_policy_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNetworkPolicyDetail:
    """Set_labels one network_policy via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_network_policy_set_labels(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_network_policy_set_labels(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            labels,
            managed_client,
        )


async def _patch_network_policy_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    network_policy_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherNetworkPolicyDetail:
    """Set_annotations one network_policy via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = {"metadata": patch_subtree}
    payload = await client.patch_json(
        networking_v1_resource_path(cluster_id, namespace, "networkpolicies", network_policy_name),
        payload=request_payload,
    )
    summary = network_policy_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherNetworkPolicyDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ingress_rule_count": summary.ingress_rule_count,
            "egress_rule_count": summary.egress_rule_count,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_network_policy_get"],
        }
    )


@audit_mutation(operation="network_policy_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_network_policy_set_annotations(
    namespace: str,
    network_policy_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNetworkPolicyDetail:
    """Set_annotations one network_policy via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_network_policy_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_network_policy_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            network_policy_name,
            annotations,
            managed_client,
        )


async def rancher_network_policies_list_tool(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherNetworkPolicyList:
    """Public MCP wrapper for curated network_policy list."""

    return await rancher_network_policies_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_network_policy_get_tool(
    namespace: str,
    network_policy_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherNetworkPolicyDetail:
    """Public MCP wrapper for curated network_policy detail."""

    return await rancher_network_policy_get(
        namespace=namespace,
        network_policy_name=network_policy_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_network_policy_delete_tool(
    namespace: str,
    network_policy_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Public MCP wrapper for curated network_policy delete."""

    return await rancher_network_policy_delete(
        namespace=namespace,
        network_policy_name=network_policy_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_network_policy_set_labels_tool(
    namespace: str,
    network_policy_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherNetworkPolicyDetail:
    """Public MCP wrapper for curated network_policy set_labels."""

    return await rancher_network_policy_set_labels(
        namespace=namespace,
        network_policy_name=network_policy_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_network_policy_set_annotations_tool(
    namespace: str,
    network_policy_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherNetworkPolicyDetail:
    """Public MCP wrapper for curated network_policy set_annotations."""

    return await rancher_network_policy_set_annotations(
        namespace=namespace,
        network_policy_name=network_policy_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
