# This file is generated by scripts/codegen from
# catalog/curated_tools/cluster_alert_rules.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cluster_alert_rule tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.alerts import RancherAlertRuleDetail, RancherAlertRuleList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.alerts.shared import (
    alert_rule_summary_from_payload,
    build_alert_rule_query_params,
    data_items,
)
from rancher_mcp.tools.support.values import mapping_value


async def _fetch_cluster_alert_rules_list(
    instance_name: str,
    limit: int | None,
    cluster_id: str | None,
    severity: str | None,
    state: str | None,
    client: ManagementDiscoveryClient,
) -> RancherAlertRuleList:
    """Fetch and normalize the Rancher cluster_alert_rules collection."""

    query_params = build_alert_rule_query_params(
        limit=limit,
        cluster_id=cluster_id,
        severity=severity,
        state=state,
    )
    payload = await client.get_json("/v3/clusteralertrules", params=query_params or None)
    cluster_alert_rules = [alert_rule_summary_from_payload(item) for item in data_items(payload)]
    return RancherAlertRuleList(
        instance=instance_name,
        alert_rule_count=len(cluster_alert_rules),
        applied_query_params=query_params,
        alert_rules=cluster_alert_rules,
        suggested_next_steps=[
            "rancher_cluster_alert_rule_get",
            "rancher_notifiers_list",
        ],
    )


async def rancher_cluster_alert_rules_list(
    limit: int | None = None,
    cluster_id: str | None = None,
    severity: str | None = None,
    state: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherAlertRuleList:
    """List cluster_alert_rules with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_alert_rules_list(
            instance_name,
            limit,
            cluster_id,
            severity,
            state,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_alert_rules_list(
            instance_name,
            limit,
            cluster_id,
            severity,
            state,
            managed_client,
        )


async def _fetch_cluster_alert_rule_get(
    instance_name: str,
    rule_id: str,
    client: ManagementDiscoveryClient,
) -> RancherAlertRuleDetail:
    """Fetch and normalize one cluster_alert_rule."""

    payload = await client.get_json(f"/v3/clusteralertrules/{rule_id}")

    status = mapping_value(payload, "status") or {}
    detail = RancherAlertRuleDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "status": dict(status),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_cluster_alert_rules_list", "rancher_notifiers_list"],
        }
    )


async def rancher_cluster_alert_rule_get(
    rule_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherAlertRuleDetail:
    """Fetch one cluster_alert_rule by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_alert_rule_get(instance_name, rule_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_alert_rule_get(
            instance_name,
            rule_id,
            managed_client,
        )


async def rancher_cluster_alert_rules_list_tool(
    limit: int | None = None,
    cluster_id: str | None = None,
    severity: str | None = None,
    state: str | None = None,
    instance: str | None = None,
) -> RancherAlertRuleList:
    """List cluster_alert_rules as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_cluster_alert_rules_list(
        limit=limit,
        cluster_id=cluster_id,
        severity=severity,
        state=state,
        instance=instance,
    )


async def rancher_cluster_alert_rule_get_tool(
    rule_id: str,
    instance: str | None = None,
) -> RancherAlertRuleDetail:
    """Fetch one cluster_alert_rule and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_cluster_alert_rule_get(
        rule_id=rule_id,
        instance=instance,
    )
