# This file is generated by scripts/codegen from
# catalog/curated_tools/notifiers.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher notifier tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.alerts import RancherNotifierDetail, RancherNotifierList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.alerts.shared import (
    build_notifier_query_params,
    data_items,
    notifier_summary_from_payload,
    notifier_types,
)
from rancher_mcp.tools.support.values import mapping_value


async def _fetch_notifiers_list(
    instance_name: str,
    limit: int | None,
    cluster_id: str | None,
    state: str | None,
    client: ManagementDiscoveryClient,
) -> RancherNotifierList:
    """Fetch and normalize the Rancher notifiers collection."""

    query_params = build_notifier_query_params(
        limit=limit,
        cluster_id=cluster_id,
        state=state,
    )
    payload = await client.get_json("/v3/notifiers", params=query_params or None)
    notifiers = [notifier_summary_from_payload(item) for item in data_items(payload)]
    return RancherNotifierList(
        instance=instance_name,
        notifier_count=len(notifiers),
        applied_query_params=query_params,
        notifiers=notifiers,
        suggested_next_steps=[
            "rancher_notifier_get",
            "rancher_cluster_alert_rules_list",
        ],
    )


async def rancher_notifiers_list(
    limit: int | None = None,
    cluster_id: str | None = None,
    state: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNotifierList:
    """List notifiers with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_notifiers_list(
            instance_name,
            limit,
            cluster_id,
            state,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_notifiers_list(
            instance_name,
            limit,
            cluster_id,
            state,
            managed_client,
        )


async def _fetch_notifier_get(
    instance_name: str,
    notifier_id: str,
    client: ManagementDiscoveryClient,
) -> RancherNotifierDetail:
    """Fetch and normalize one notifier."""

    payload = await client.get_json(f"/v3/notifiers/{notifier_id}")

    status = mapping_value(payload, "status") or {}
    detail = RancherNotifierDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "notifier_types": notifier_types(payload),
            "status": dict(status),
            "action_keys": sorted(mapping_value(payload, "actions") or {}),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_notifiers_list", "rancher_cluster_alert_rules_list"],
        }
    )


async def rancher_notifier_get(
    notifier_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNotifierDetail:
    """Fetch one notifier by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_notifier_get(instance_name, notifier_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_notifier_get(
            instance_name,
            notifier_id,
            managed_client,
        )


async def rancher_notifiers_list_tool(
    limit: int | None = None,
    cluster_id: str | None = None,
    state: str | None = None,
    instance: str | None = None,
) -> RancherNotifierList:
    """Public MCP wrapper for curated notifier list."""

    return await rancher_notifiers_list(
        limit=limit,
        cluster_id=cluster_id,
        state=state,
        instance=instance,
    )


async def rancher_notifier_get_tool(
    notifier_id: str,
    instance: str | None = None,
) -> RancherNotifierDetail:
    """Public MCP wrapper for curated notifier detail."""

    return await rancher_notifier_get(
        notifier_id=notifier_id,
        instance=instance,
    )
