# This file is generated by scripts/codegen from
# catalog/curated_tools/services.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher service tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.steve import RancherSteveClient, SteveMutationClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.pods_services import RancherServiceDetail, RancherServiceList
from rancher_mcp.models.resources import RancherCuratedDeleteResult, RancherMutationReceipt
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resource_queries import build_steve_list_query_params
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.pods_services.shared import (
    data_items,
    relationship_types,
    service_summary_from_payload,
)
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value


async def _fetch_services_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit: int | None,
    label_selector: str | None,
    client: SteveMutationClient,
    page_token: str | None = None,
) -> RancherServiceList:
    """Fetch and normalize the services collection for one namespace."""

    query_params = build_steve_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(f"/services/{namespace}", params=query_params or None)
    services = [service_summary_from_payload(item) for item in data_items(payload)]
    return RancherServiceList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        service_count=len(services),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        services=services,
        suggested_next_steps=[
            "rancher_service_get",
            "rancher_pods_list",
            "rancher_deployments_list",
        ],
    )


async def rancher_services_list(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherServiceList:
    """List services in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_services_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _fetch_services_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            steve_client,
            page_token,
        )


async def _fetch_service_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    client: SteveMutationClient,
) -> RancherServiceDetail:
    """Fetch and normalize one service."""

    payload = await client.get_json(f"/services/{namespace}/{service_name}")
    summary = service_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    detail = RancherServiceDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "id": summary.id,
            "relationship_types": relationship_types(metadata),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_services_list", "rancher_pods_list"],
        }
    )


async def rancher_service_get(
    namespace: str,
    service_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherServiceDetail:
    """Fetch one service by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_service_get(instance_name, cluster_id, namespace, service_name, client)
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _fetch_service_get(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            steve_client,
        )


async def _delete_service(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    confirmation_phrase_used: str,
    client: SteveMutationClient,
) -> RancherCuratedDeleteResult:
    """Delete one service; returns a typed delete result."""

    response_payload = await client.delete_json(f"/services/{namespace}/{service_name}")
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="service",
        resource_name=service_name,
        namespace=namespace,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_services_list"],
    )


@audit_mutation(operation="service_delete", plane="steve")
@rate_limit_writes
async def rancher_service_delete(
    namespace: str,
    service_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one service after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete service {service_name} in namespace {namespace}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_service(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            expected_phrase,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _delete_service(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            expected_phrase,
            steve_client,
        )


async def _patch_service_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    labels: dict[str, str],
    client: SteveMutationClient,
) -> RancherMutationReceipt:
    """Set_labels one service via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(f"/services/{namespace}/{service_name}"),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="service",
        action="set_labels",
        name=service_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(f"/services/{namespace}/{service_name}", payload=request_payload)
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="service",
        name=service_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="service_set_labels", plane="steve")
@rate_limit_writes
async def rancher_service_set_labels(
    namespace: str,
    service_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one service via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_service_set_labels(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            labels,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _patch_service_set_labels(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            labels,
            steve_client,
        )


async def _patch_service_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    annotations: dict[str, str],
    client: SteveMutationClient,
) -> RancherMutationReceipt:
    """Set_annotations one service via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(f"/services/{namespace}/{service_name}"),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="service",
        action="set_annotations",
        name=service_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(f"/services/{namespace}/{service_name}", payload=request_payload)
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="service",
        name=service_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="service_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_service_set_annotations(
    namespace: str,
    service_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one service via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_service_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            annotations,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _patch_service_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            annotations,
            steve_client,
        )


async def _patch_service_set_type(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    type: str,
    client: SteveMutationClient,
) -> RancherMutationReceipt:
    """Set_type one service via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["type"] = type
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"spec": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(f"/services/{namespace}/{service_name}"),
        target_path="spec",
        patch_subtree=patch_subtree,
        kind="service",
        action="set_type",
        name=service_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(f"/services/{namespace}/{service_name}", payload=request_payload)
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_type",
        kind="service",
        name=service_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="service_set_type", plane="steve")
@rate_limit_writes
async def rancher_service_set_type(
    namespace: str,
    service_name: str,
    type: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherMutationReceipt:
    """Set_type one service via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_service_set_type(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            type,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _patch_service_set_type(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            type,
            steve_client,
        )


async def rancher_services_list_tool(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherServiceList:
    """List services as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_services_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_service_get_tool(
    namespace: str,
    service_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherServiceDetail:
    """Fetch one service and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_service_get(
        namespace=namespace,
        service_name=service_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_service_delete_tool(
    namespace: str,
    service_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one service and return a typed receipt of what was removed. Destructive and irreversible — the caller must first echo the exact confirmation phrase the tool requires."""

    return await rancher_service_delete(
        namespace=namespace,
        service_name=service_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_service_set_labels_tool(
    namespace: str,
    service_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one service in place (set labels) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_service_set_labels(
        namespace=namespace,
        service_name=service_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_service_set_annotations_tool(
    namespace: str,
    service_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one service in place (set annotations) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_service_set_annotations(
        namespace=namespace,
        service_name=service_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_service_set_type_tool(
    namespace: str,
    service_name: str,
    type: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one service in place (set type) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_service_set_type(
        namespace=namespace,
        service_name=service_name,
        type=type,
        cluster_id=cluster_id,
        instance=instance,
    )
