# This file is generated by scripts/codegen from
# catalog/curated_tools/services.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher service tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.steve import RancherSteveClient, SteveMutationClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.pods_services import RancherServiceDetail, RancherServiceList
from rancher_mcp.models.resources import RancherMutationReceipt
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resource_queries import build_steve_list_query_params
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.pods_services.shared import (
    data_items,
    relationship_types,
    service_summary_from_payload,
)
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value


async def _fetch_services_list(
    instance_name: str,
    cluster_id: str,
    namespace: str | None,
    limit: int | None,
    label_selector: str | None,
    client: SteveMutationClient,
    page_token: str | None = None,
) -> RancherServiceList:
    """Fetch and normalize the services collection for one namespace, or cluster-wide when namespace is omitted."""

    query_params = build_steve_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    # namespace=None means cluster-wide (all namespaces) — the "/{namespace}"
    # suffix is dropped rather than defaulted, so a whole-cluster triage
    # query never silently narrows to one namespace.
    list_request_path = f"/services/{namespace}" if namespace is not None else "/services"
    payload = await client.get_json(list_request_path, params=query_params or None)
    services = [service_summary_from_payload(item) for item in data_items(payload)]
    return RancherServiceList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        service_count=len(services),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        services=services,
        suggested_next_steps=[
            "rancher_service_get",
            "rancher_pods_list",
            "rancher_deployments_list",
        ],
    )


async def rancher_services_list(
    namespace: str | None = None,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherServiceList:
    """List services with typed summaries — in one namespace, or cluster-wide when namespace is omitted."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_services_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _fetch_services_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            steve_client,
            page_token,
        )


async def _fetch_service_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    client: SteveMutationClient,
) -> RancherServiceDetail:
    """Fetch and normalize one service."""

    payload = await client.get_json(f"/services/{namespace}/{service_name}")
    summary = service_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    detail = RancherServiceDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "id": summary.id,
            "relationship_types": relationship_types(metadata),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "payload": dict(payload),
            "cluster_id": cluster_id,
            "suggested_next_steps": ["rancher_services_list", "rancher_pods_list"],
        }
    )


async def rancher_service_get(
    namespace: str,
    service_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherServiceDetail:
    """Fetch one service by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_service_get(instance_name, cluster_id, namespace, service_name, client)
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _fetch_service_get(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            steve_client,
        )


async def _patch_service_set_type(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    service_name: str,
    type: str,
    client: SteveMutationClient,
) -> RancherMutationReceipt:
    """Set_type one service via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["type"] = type
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"spec": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(f"/services/{namespace}/{service_name}"),
        target_path="spec",
        patch_subtree=patch_subtree,
        kind="service",
        action="set_type",
        name=service_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(f"/services/{namespace}/{service_name}", payload=request_payload)
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_type",
        kind="service",
        name=service_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
        suggested_next_steps=["rancher_service_get"],
    )


@audit_mutation(operation="service_set_type", plane="steve")
@rate_limit_writes
async def rancher_service_set_type(
    namespace: str,
    service_name: str,
    type: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: SteveMutationClient | None = None,
) -> RancherMutationReceipt:
    """Set_type one service via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_service_set_type(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            type,
            client,
        )
    async with RancherSteveClient(
        instance_name,
        instance_config,
        cluster_id=cluster_id,
    ) as steve_client:
        return await _patch_service_set_type(
            instance_name,
            cluster_id,
            namespace,
            service_name,
            type,
            steve_client,
        )


async def rancher_services_list_tool(
    namespace: str | None = None,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherServiceList:
    """List services as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool. Omit `namespace` to list across the whole cluster; pass it to scope to one namespace."""

    return await rancher_services_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_service_get_tool(
    namespace: str,
    service_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherServiceDetail:
    """Fetch one service and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_service_get(
        namespace=namespace,
        service_name=service_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_service_set_type_tool(
    namespace: str,
    service_name: str,
    type: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one service in place (set type) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_service_set_type(
        namespace=namespace,
        service_name=service_name,
        type=type,
        cluster_id=cluster_id,
        instance=instance,
    )
