# This file is generated by scripts/codegen from
# catalog/curated_tools/_packs/disruption.yml plus all per-resource
# descriptors in the same pack. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher disruption-management read-only tools."""

from mcp.server.fastmcp import FastMCP

from rancher_mcp.tools.disruption._generated_pod_disruption_budgets import (
    rancher_pod_disruption_budget_get,
    rancher_pod_disruption_budget_get_tool,
    rancher_pod_disruption_budgets_list,
    rancher_pod_disruption_budgets_list_tool,
)
from rancher_mcp.tools.support.annotations import READ_ONLY

__all__ = [
    "rancher_pod_disruption_budget_get",
    "rancher_pod_disruption_budgets_list",
    "register_disruption_tools",
]


def register_disruption_tools(mcp: FastMCP) -> None:
    """Register curated disruption-management tools with the FastMCP server."""

    mcp.tool(name="rancher_pod_disruption_budgets_list", annotations=READ_ONLY)(
        rancher_pod_disruption_budgets_list_tool
    )
    mcp.tool(name="rancher_pod_disruption_budget_get", annotations=READ_ONLY)(
        rancher_pod_disruption_budget_get_tool
    )
