# This file is generated by scripts/codegen from
# catalog/curated_tools/_packs/governance.yml plus all per-resource
# descriptors in the same pack. Do not edit by hand.
# Regenerate with: make codegen

"""Curated cluster-governance tools (HPA, ResourceQuota, LimitRange)."""

from mcp.server.fastmcp import FastMCP

from rancher_mcp.tools.governance._generated_horizontal_pod_autoscalers import (
    rancher_horizontal_pod_autoscaler_get,
    rancher_horizontal_pod_autoscaler_get_tool,
    rancher_horizontal_pod_autoscaler_set_annotations,
    rancher_horizontal_pod_autoscaler_set_annotations_tool,
    rancher_horizontal_pod_autoscaler_set_labels,
    rancher_horizontal_pod_autoscaler_set_labels_tool,
    rancher_horizontal_pod_autoscalers_list,
    rancher_horizontal_pod_autoscalers_list_tool,
)
from rancher_mcp.tools.governance._generated_limit_ranges import (
    rancher_limit_range_get,
    rancher_limit_range_get_tool,
    rancher_limit_ranges_list,
    rancher_limit_ranges_list_tool,
)
from rancher_mcp.tools.governance._generated_resource_quotas import (
    rancher_resource_quota_get,
    rancher_resource_quota_get_tool,
    rancher_resource_quota_set_labels,
    rancher_resource_quota_set_labels_tool,
    rancher_resource_quotas_list,
    rancher_resource_quotas_list_tool,
)
from rancher_mcp.tools.support.annotations import IDEMPOTENT_WRITE, READ_ONLY

__all__ = [
    "rancher_horizontal_pod_autoscaler_get",
    "rancher_horizontal_pod_autoscaler_set_annotations",
    "rancher_horizontal_pod_autoscaler_set_labels",
    "rancher_horizontal_pod_autoscalers_list",
    "rancher_limit_range_get",
    "rancher_limit_ranges_list",
    "rancher_resource_quota_get",
    "rancher_resource_quota_set_labels",
    "rancher_resource_quotas_list",
    "register_governance_tools",
]


def register_governance_tools(mcp: FastMCP) -> None:
    """Register curated cluster-governance tools with the FastMCP server."""

    mcp.tool(name="rancher_horizontal_pod_autoscalers_list", annotations=READ_ONLY)(
        rancher_horizontal_pod_autoscalers_list_tool
    )
    mcp.tool(name="rancher_horizontal_pod_autoscaler_get", annotations=READ_ONLY)(
        rancher_horizontal_pod_autoscaler_get_tool
    )
    mcp.tool(name="rancher_horizontal_pod_autoscaler_set_labels", annotations=IDEMPOTENT_WRITE)(
        rancher_horizontal_pod_autoscaler_set_labels_tool
    )
    mcp.tool(
        name="rancher_horizontal_pod_autoscaler_set_annotations", annotations=IDEMPOTENT_WRITE
    )(rancher_horizontal_pod_autoscaler_set_annotations_tool)
    mcp.tool(name="rancher_limit_ranges_list", annotations=READ_ONLY)(
        rancher_limit_ranges_list_tool
    )
    mcp.tool(name="rancher_limit_range_get", annotations=READ_ONLY)(rancher_limit_range_get_tool)
    mcp.tool(name="rancher_resource_quotas_list", annotations=READ_ONLY)(
        rancher_resource_quotas_list_tool
    )
    mcp.tool(name="rancher_resource_quota_get", annotations=READ_ONLY)(
        rancher_resource_quota_get_tool
    )
    mcp.tool(name="rancher_resource_quota_set_labels", annotations=IDEMPOTENT_WRITE)(
        rancher_resource_quota_set_labels_tool
    )
