# This file is generated by scripts/codegen from
# catalog/curated_tools/resource_quotas.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher resource_quota tools."""

from __future__ import annotations

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.governance import RancherResourceQuotaDetail, RancherResourceQuotaList
from rancher_mcp.models.resources import RancherCuratedDeleteResult
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.governance.paths import core_v1_collection_path, core_v1_resource_path
from rancher_mcp.tools.governance.shared import (
    build_list_query_params,
    items,
    resource_quota_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_resource_quotas_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherResourceQuotaList:
    """Fetch and normalize resource_quotas through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        core_v1_collection_path(cluster_id, namespace, "resourcequotas"),
        params=query_params or None,
    )
    resource_quotas = [resource_quota_summary_from_payload(item) for item in items(payload)]
    return RancherResourceQuotaList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        resource_quota_count=len(resource_quotas),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        resource_quotas=resource_quotas,
        suggested_next_steps=[
            "rancher_resource_quota_get",
            "rancher_pods_list",
        ],
    )


async def rancher_resource_quotas_list(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherResourceQuotaList:
    """List resource_quotas in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_resource_quotas_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_resource_quotas_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_resource_quota_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    resource_quota_name: str,
    client: ManagementDiscoveryClient,
) -> RancherResourceQuotaDetail:
    """Fetch and normalize one resource_quota."""

    payload = await client.get_json(
        core_v1_resource_path(cluster_id, namespace, "resourcequotas", resource_quota_name)
    )
    summary = resource_quota_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherResourceQuotaDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "hard_limit_count": summary.hard_limit_count,
            "used_count": summary.used_count,
            "hard_limit_keys": summary.hard_limit_keys,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_resource_quotas_list", "rancher_pods_list"],
        }
    )


async def rancher_resource_quota_get(
    namespace: str,
    resource_quota_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherResourceQuotaDetail:
    """Fetch one resource_quota by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_resource_quota_get(
            instance_name, cluster_id, namespace, resource_quota_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_resource_quota_get(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            managed_client,
        )


async def _delete_resource_quota(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    resource_quota_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one resource_quota; returns a typed delete result."""

    response_payload = await client.delete_json(
        core_v1_resource_path(cluster_id, namespace, "resourcequotas", resource_quota_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="resource_quota",
        resource_name=resource_quota_name,
        namespace=namespace,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_resource_quotas_list"],
    )


@audit_mutation(operation="resource_quota_delete", plane="steve")
@rate_limit_writes
async def rancher_resource_quota_delete(
    namespace: str,
    resource_quota_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one resource_quota after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete resource_quota {resource_quota_name} in namespace {namespace}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_resource_quota(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_resource_quota(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            expected_phrase,
            managed_client,
        )


async def _patch_resource_quota_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    resource_quota_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherResourceQuotaDetail:
    """Set_labels one resource_quota via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    payload = await client.patch_json(
        core_v1_resource_path(cluster_id, namespace, "resourcequotas", resource_quota_name),
        payload=request_payload,
    )
    summary = resource_quota_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherResourceQuotaDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "hard_limit_count": summary.hard_limit_count,
            "used_count": summary.used_count,
            "hard_limit_keys": summary.hard_limit_keys,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_resource_quota_get", "rancher_resource_quotas_list"],
        }
    )


@audit_mutation(operation="resource_quota_set_labels", plane="steve")
@rate_limit_writes
async def rancher_resource_quota_set_labels(
    namespace: str,
    resource_quota_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherResourceQuotaDetail:
    """Set_labels one resource_quota via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_resource_quota_set_labels(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_resource_quota_set_labels(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            labels,
            managed_client,
        )


async def _patch_resource_quota_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    resource_quota_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherResourceQuotaDetail:
    """Set_annotations one resource_quota via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    payload = await client.patch_json(
        core_v1_resource_path(cluster_id, namespace, "resourcequotas", resource_quota_name),
        payload=request_payload,
    )
    summary = resource_quota_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherResourceQuotaDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "hard_limit_count": summary.hard_limit_count,
            "used_count": summary.used_count,
            "hard_limit_keys": summary.hard_limit_keys,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_resource_quota_get"],
        }
    )


@audit_mutation(operation="resource_quota_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_resource_quota_set_annotations(
    namespace: str,
    resource_quota_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherResourceQuotaDetail:
    """Set_annotations one resource_quota via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_resource_quota_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_resource_quota_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            resource_quota_name,
            annotations,
            managed_client,
        )


async def rancher_resource_quotas_list_tool(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherResourceQuotaList:
    """Public MCP wrapper for curated resource_quota list."""

    return await rancher_resource_quotas_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_resource_quota_get_tool(
    namespace: str,
    resource_quota_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherResourceQuotaDetail:
    """Public MCP wrapper for curated resource_quota detail."""

    return await rancher_resource_quota_get(
        namespace=namespace,
        resource_quota_name=resource_quota_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_resource_quota_delete_tool(
    namespace: str,
    resource_quota_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Public MCP wrapper for curated resource_quota delete."""

    return await rancher_resource_quota_delete(
        namespace=namespace,
        resource_quota_name=resource_quota_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_resource_quota_set_labels_tool(
    namespace: str,
    resource_quota_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherResourceQuotaDetail:
    """Public MCP wrapper for curated resource_quota set_labels."""

    return await rancher_resource_quota_set_labels(
        namespace=namespace,
        resource_quota_name=resource_quota_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_resource_quota_set_annotations_tool(
    namespace: str,
    resource_quota_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherResourceQuotaDetail:
    """Public MCP wrapper for curated resource_quota set_annotations."""

    return await rancher_resource_quota_set_annotations(
        namespace=namespace,
        resource_quota_name=resource_quota_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
