# This file is generated by scripts/codegen from
# catalog/curated_tools/limit_ranges.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher limit_range tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.governance import RancherLimitRangeDetail, RancherLimitRangeList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.governance.paths import core_v1_collection_path, core_v1_resource_path
from rancher_mcp.tools.governance.shared import (
    build_list_query_params,
    items,
    limit_range_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_limit_ranges_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherLimitRangeList:
    """Fetch and normalize limit_ranges through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        core_v1_collection_path(cluster_id, namespace, "limitranges"),
        params=query_params or None,
    )
    limit_ranges = [limit_range_summary_from_payload(item) for item in items(payload)]
    return RancherLimitRangeList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        limit_range_count=len(limit_ranges),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        limit_ranges=limit_ranges,
        suggested_next_steps=[
            "rancher_limit_range_get",
            "rancher_resource_quotas_list",
        ],
    )


async def rancher_limit_ranges_list(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLimitRangeList:
    """List limit_ranges in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_limit_ranges_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_limit_ranges_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_limit_range_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit_range_name: str,
    client: ManagementDiscoveryClient,
) -> RancherLimitRangeDetail:
    """Fetch and normalize one limit_range."""

    payload = await client.get_json(
        core_v1_resource_path(cluster_id, namespace, "limitranges", limit_range_name)
    )
    summary = limit_range_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherLimitRangeDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "limit_count": summary.limit_count,
            "types_present": summary.types_present,
            "annotation_keys": sorted(string_dict(annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_limit_ranges_list", "rancher_resource_quotas_list"],
        }
    )


async def rancher_limit_range_get(
    namespace: str,
    limit_range_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLimitRangeDetail:
    """Fetch one limit_range by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_limit_range_get(
            instance_name, cluster_id, namespace, limit_range_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_limit_range_get(
            instance_name,
            cluster_id,
            namespace,
            limit_range_name,
            managed_client,
        )


async def rancher_limit_ranges_list_tool(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherLimitRangeList:
    """Public MCP wrapper for curated limit_range list."""

    return await rancher_limit_ranges_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_limit_range_get_tool(
    namespace: str,
    limit_range_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherLimitRangeDetail:
    """Public MCP wrapper for curated limit_range detail."""

    return await rancher_limit_range_get(
        namespace=namespace,
        limit_range_name=limit_range_name,
        cluster_id=cluster_id,
        instance=instance,
    )
