# This file is generated by scripts/codegen from
# catalog/curated_tools/_packs/logging_pipeline.yml plus all per-resource
# descriptors in the same pack. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Banzai logging-pipeline tools (Output, ClusterOutput, Flow, ClusterFlow)."""

from mcp.server.fastmcp import FastMCP

from rancher_mcp.tools.logging_pipeline._generated_cluster_flows import (
    rancher_cluster_flow_get,
    rancher_cluster_flow_get_tool,
    rancher_cluster_flows_list,
    rancher_cluster_flows_list_tool,
)
from rancher_mcp.tools.logging_pipeline._generated_cluster_outputs import (
    rancher_cluster_output_get,
    rancher_cluster_output_get_tool,
    rancher_cluster_outputs_list,
    rancher_cluster_outputs_list_tool,
)
from rancher_mcp.tools.logging_pipeline._generated_flows import (
    rancher_flow_get,
    rancher_flow_get_tool,
    rancher_flow_set_labels,
    rancher_flow_set_labels_tool,
    rancher_flows_list,
    rancher_flows_list_tool,
)
from rancher_mcp.tools.logging_pipeline._generated_outputs import (
    rancher_output_get,
    rancher_output_get_tool,
    rancher_outputs_list,
    rancher_outputs_list_tool,
)
from rancher_mcp.tools.support.annotations import IDEMPOTENT_WRITE, READ_ONLY

__all__ = [
    "rancher_cluster_flow_get",
    "rancher_cluster_flows_list",
    "rancher_cluster_output_get",
    "rancher_cluster_outputs_list",
    "rancher_flow_get",
    "rancher_flow_set_labels",
    "rancher_flows_list",
    "rancher_output_get",
    "rancher_outputs_list",
    "register_logging_pipeline_tools",
]


def register_logging_pipeline_tools(mcp: FastMCP) -> None:
    """Register curated logging-pipeline tools with the FastMCP server."""

    mcp.tool(name="rancher_cluster_flows_list", annotations=READ_ONLY)(
        rancher_cluster_flows_list_tool
    )
    mcp.tool(name="rancher_cluster_flow_get", annotations=READ_ONLY)(rancher_cluster_flow_get_tool)
    mcp.tool(name="rancher_cluster_outputs_list", annotations=READ_ONLY)(
        rancher_cluster_outputs_list_tool
    )
    mcp.tool(name="rancher_cluster_output_get", annotations=READ_ONLY)(
        rancher_cluster_output_get_tool
    )
    mcp.tool(name="rancher_flows_list", annotations=READ_ONLY)(rancher_flows_list_tool)
    mcp.tool(name="rancher_flow_get", annotations=READ_ONLY)(rancher_flow_get_tool)
    mcp.tool(name="rancher_flow_set_labels", annotations=IDEMPOTENT_WRITE)(
        rancher_flow_set_labels_tool
    )
    mcp.tool(name="rancher_outputs_list", annotations=READ_ONLY)(rancher_outputs_list_tool)
    mcp.tool(name="rancher_output_get", annotations=READ_ONLY)(rancher_output_get_tool)
