# This file is generated by scripts/codegen from
# catalog/curated_tools/flows.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher flow tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.logging_pipeline import RancherLoggingFlowDetail, RancherLoggingFlowList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.logging_pipeline.paths import (
    logging_namespaced_collection_path,
    logging_namespaced_resource_path,
)
from rancher_mcp.tools.logging_pipeline.shared import (
    build_list_query_params,
    flow_summary_from_payload,
    items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_flows_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherLoggingFlowList:
    """Fetch and normalize flows through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        logging_namespaced_collection_path(cluster_id, namespace, "flows"),
        params=query_params or None,
    )
    flows = [flow_summary_from_payload(item) for item in items(payload)]
    return RancherLoggingFlowList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        flow_count=len(flows),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        flows=flows,
        suggested_next_steps=[
            "rancher_flow_get",
            "rancher_outputs_list",
        ],
    )


async def rancher_flows_list(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLoggingFlowList:
    """List flows in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_flows_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_flows_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_flow_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    flow_name: str,
    client: ManagementDiscoveryClient,
) -> RancherLoggingFlowDetail:
    """Fetch and normalize one flow."""

    payload = await client.get_json(
        logging_namespaced_resource_path(cluster_id, namespace, "flows", flow_name)
    )
    summary = flow_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherLoggingFlowDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "match_count": summary.match_count,
            "filter_count": summary.filter_count,
            "annotation_keys": sorted(string_dict(annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_flows_list", "rancher_outputs_list"],
        }
    )


async def rancher_flow_get(
    namespace: str,
    flow_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLoggingFlowDetail:
    """Fetch one flow by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_flow_get(instance_name, cluster_id, namespace, flow_name, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_flow_get(
            instance_name,
            cluster_id,
            namespace,
            flow_name,
            managed_client,
        )


async def rancher_flows_list_tool(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherLoggingFlowList:
    """Public MCP wrapper for curated flow list."""

    return await rancher_flows_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_flow_get_tool(
    namespace: str,
    flow_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherLoggingFlowDetail:
    """Public MCP wrapper for curated flow detail."""

    return await rancher_flow_get(
        namespace=namespace,
        flow_name=flow_name,
        cluster_id=cluster_id,
        instance=instance,
    )
