# This file is generated by scripts/codegen from
# catalog/curated_tools/cluster_flows.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cluster_flow tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.logging_pipeline import (
    RancherLoggingClusterFlowDetail,
    RancherLoggingClusterFlowList,
)
from rancher_mcp.models.resources import RancherCuratedDeleteResult, RancherMutationReceipt
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.logging_pipeline.paths import (
    logging_cluster_collection_path,
    logging_cluster_resource_path,
)
from rancher_mcp.tools.logging_pipeline.shared import (
    build_list_query_params,
    cluster_flow_summary_from_payload,
    items,
)
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_cluster_flows_list(
    instance_name: str,
    cluster_id: str,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherLoggingClusterFlowList:
    """Fetch and normalize cluster_flows through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        logging_cluster_collection_path(cluster_id, "clusterflows"),
        params=query_params or None,
    )
    cluster_flows = [cluster_flow_summary_from_payload(item) for item in items(payload)]
    return RancherLoggingClusterFlowList(
        instance=instance_name,
        cluster_id=cluster_id,
        cluster_flow_count=len(cluster_flows),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        cluster_flows=cluster_flows,
        suggested_next_steps=[
            "rancher_cluster_flow_get",
            "rancher_cluster_outputs_list",
        ],
    )


async def rancher_cluster_flows_list(
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLoggingClusterFlowList:
    """List cluster_flows with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_flows_list(
            instance_name,
            cluster_id,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_flows_list(
            instance_name,
            cluster_id,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_cluster_flow_get(
    instance_name: str,
    cluster_id: str,
    cluster_flow_name: str,
    client: ManagementDiscoveryClient,
) -> RancherLoggingClusterFlowDetail:
    """Fetch and normalize one cluster_flow."""

    payload = await client.get_json(
        logging_cluster_resource_path(cluster_id, "clusterflows", cluster_flow_name)
    )
    summary = cluster_flow_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherLoggingClusterFlowDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "match_count": summary.match_count,
            "filter_count": summary.filter_count,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "cluster_id": cluster_id,
            "suggested_next_steps": ["rancher_cluster_flows_list", "rancher_cluster_outputs_list"],
        }
    )


async def rancher_cluster_flow_get(
    cluster_flow_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherLoggingClusterFlowDetail:
    """Fetch one cluster_flow by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_flow_get(instance_name, cluster_id, cluster_flow_name, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_flow_get(
            instance_name,
            cluster_id,
            cluster_flow_name,
            managed_client,
        )


async def _delete_cluster_flow(
    instance_name: str,
    cluster_id: str,
    cluster_flow_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one cluster_flow; returns a typed delete result."""

    response_payload = await client.delete_json(
        logging_cluster_resource_path(cluster_id, "clusterflows", cluster_flow_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="cluster_flow",
        resource_name=cluster_flow_name,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_cluster_flows_list"],
    )


@audit_mutation(operation="cluster_flow_delete", plane="steve")
@rate_limit_writes
async def rancher_cluster_flow_delete(
    cluster_flow_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one cluster_flow after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete cluster_flow {cluster_flow_name}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_cluster_flow(
            instance_name,
            cluster_id,
            cluster_flow_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_cluster_flow(
            instance_name,
            cluster_id,
            cluster_flow_name,
            expected_phrase,
            managed_client,
        )


async def _patch_cluster_flow_set_labels(
    instance_name: str,
    cluster_id: str,
    cluster_flow_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_labels one cluster_flow via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            logging_cluster_resource_path(cluster_id, "clusterflows", cluster_flow_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="cluster_flow",
        action="set_labels",
        name=cluster_flow_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        logging_cluster_resource_path(cluster_id, "clusterflows", cluster_flow_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="cluster_flow",
        name=cluster_flow_name,
        cluster_id=cluster_id,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="cluster_flow_set_labels", plane="steve")
@rate_limit_writes
async def rancher_cluster_flow_set_labels(
    cluster_flow_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one cluster_flow via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_cluster_flow_set_labels(
            instance_name,
            cluster_id,
            cluster_flow_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_cluster_flow_set_labels(
            instance_name,
            cluster_id,
            cluster_flow_name,
            labels,
            managed_client,
        )


async def _patch_cluster_flow_set_annotations(
    instance_name: str,
    cluster_id: str,
    cluster_flow_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_annotations one cluster_flow via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            logging_cluster_resource_path(cluster_id, "clusterflows", cluster_flow_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="cluster_flow",
        action="set_annotations",
        name=cluster_flow_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        logging_cluster_resource_path(cluster_id, "clusterflows", cluster_flow_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="cluster_flow",
        name=cluster_flow_name,
        cluster_id=cluster_id,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="cluster_flow_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_cluster_flow_set_annotations(
    cluster_flow_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one cluster_flow via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_cluster_flow_set_annotations(
            instance_name,
            cluster_id,
            cluster_flow_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_cluster_flow_set_annotations(
            instance_name,
            cluster_id,
            cluster_flow_name,
            annotations,
            managed_client,
        )


async def rancher_cluster_flows_list_tool(
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherLoggingClusterFlowList:
    """List cluster_flows as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_cluster_flows_list(
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_cluster_flow_get_tool(
    cluster_flow_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherLoggingClusterFlowDetail:
    """Fetch one cluster_flow and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_cluster_flow_get(
        cluster_flow_name=cluster_flow_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cluster_flow_delete_tool(
    cluster_flow_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one cluster_flow and return a typed receipt of what was removed. Destructive and irreversible — the caller must first echo the exact confirmation phrase the tool requires."""

    return await rancher_cluster_flow_delete(
        cluster_flow_name=cluster_flow_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cluster_flow_set_labels_tool(
    cluster_flow_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one cluster_flow in place (set labels) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_cluster_flow_set_labels(
        cluster_flow_name=cluster_flow_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cluster_flow_set_annotations_tool(
    cluster_flow_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one cluster_flow in place (set annotations) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_cluster_flow_set_annotations(
        cluster_flow_name=cluster_flow_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
