# This file is generated by scripts/codegen from
# catalog/curated_tools/restores.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher restore tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.backup_operator import RancherRestoreDetail, RancherRestoreList
from rancher_mcp.models.resources import RancherMutationReceipt
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.backup_operator.paths import (
    resources_cattle_io_v1_collection_path,
    resources_cattle_io_v1_resource_path,
)
from rancher_mcp.tools.backup_operator.shared import (
    build_list_query_params,
    condition_types_true,
    conditions_from_payload,
    items,
    restore_summary_from_payload,
    storage_location_summary,
)
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_restores_list(
    instance_name: str,
    cluster_id: str,
    limit: int | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherRestoreList:
    """Fetch and normalize restores through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
    )
    payload = await client.get_json(
        resources_cattle_io_v1_collection_path(cluster_id, "restores"),
        params=query_params or None,
    )
    restores = [restore_summary_from_payload(item) for item in items(payload)]
    return RancherRestoreList(
        instance=instance_name,
        cluster_id=cluster_id,
        restore_count=len(restores),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        restores=restores,
        suggested_next_steps=[
            "rancher_restore_get",
            "rancher_backups_list",
        ],
    )


async def rancher_restores_list(
    cluster_id: str = "local",
    limit: int | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherRestoreList:
    """List restores with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_restores_list(
            instance_name,
            cluster_id,
            limit,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_restores_list(
            instance_name,
            cluster_id,
            limit,
            managed_client,
            page_token,
        )


async def _fetch_restore_get(
    instance_name: str,
    cluster_id: str,
    restore_name: str,
    client: ManagementDiscoveryClient,
) -> RancherRestoreDetail:
    """Fetch and normalize one restore."""

    payload = await client.get_json(
        resources_cattle_io_v1_resource_path(cluster_id, "restores", restore_name)
    )
    summary = restore_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherRestoreDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "summary_state": summary.summary_state,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "condition_types_true": condition_types_true(conditions_from_payload(payload)),
            "storage_location_summary": storage_location_summary(payload),
            "payload": dict(payload),
            "cluster_id": cluster_id,
            "suggested_next_steps": ["rancher_restores_list", "rancher_backups_list"],
        }
    )


async def rancher_restore_get(
    restore_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherRestoreDetail:
    """Fetch one restore by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_restore_get(instance_name, cluster_id, restore_name, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_restore_get(
            instance_name,
            cluster_id,
            restore_name,
            managed_client,
        )


async def _patch_restore_set_labels(
    instance_name: str,
    cluster_id: str,
    restore_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_labels one restore via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            resources_cattle_io_v1_resource_path(cluster_id, "restores", restore_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="restore",
        action="set_labels",
        name=restore_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        resources_cattle_io_v1_resource_path(cluster_id, "restores", restore_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="restore",
        name=restore_name,
        cluster_id=cluster_id,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="restore_set_labels", plane="steve")
@rate_limit_writes
async def rancher_restore_set_labels(
    restore_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one restore via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_restore_set_labels(
            instance_name,
            cluster_id,
            restore_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_restore_set_labels(
            instance_name,
            cluster_id,
            restore_name,
            labels,
            managed_client,
        )


async def _patch_restore_set_annotations(
    instance_name: str,
    cluster_id: str,
    restore_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_annotations one restore via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            resources_cattle_io_v1_resource_path(cluster_id, "restores", restore_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="restore",
        action="set_annotations",
        name=restore_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        resources_cattle_io_v1_resource_path(cluster_id, "restores", restore_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="restore",
        name=restore_name,
        cluster_id=cluster_id,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="restore_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_restore_set_annotations(
    restore_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one restore via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_restore_set_annotations(
            instance_name,
            cluster_id,
            restore_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_restore_set_annotations(
            instance_name,
            cluster_id,
            restore_name,
            annotations,
            managed_client,
        )


async def rancher_restores_list_tool(
    cluster_id: str = "local",
    limit: int | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherRestoreList:
    """List restores as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_restores_list(
        cluster_id=cluster_id,
        limit=limit,
        page_token=page_token,
        instance=instance,
    )


async def rancher_restore_get_tool(
    restore_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherRestoreDetail:
    """Fetch one restore and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_restore_get(
        restore_name=restore_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_restore_set_labels_tool(
    restore_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one restore in place (set labels) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_restore_set_labels(
        restore_name=restore_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_restore_set_annotations_tool(
    restore_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one restore in place (set annotations) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_restore_set_annotations(
        restore_name=restore_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
