# This file is generated by scripts/codegen from
# catalog/curated_tools/_packs/cert_manager.yml plus all per-resource
# descriptors in the same pack. Do not edit by hand.
# Regenerate with: make codegen

"""Curated cert-manager tools (Certificate, Issuer, ClusterIssuer at cert-manager.io/v1)."""

from mcp.server.fastmcp import FastMCP

from rancher_mcp.tools.cert_manager._generated_cert_manager_certificates import (
    rancher_cert_manager_certificate_get,
    rancher_cert_manager_certificate_get_tool,
    rancher_cert_manager_certificate_set_annotations,
    rancher_cert_manager_certificate_set_annotations_tool,
    rancher_cert_manager_certificate_set_labels,
    rancher_cert_manager_certificate_set_labels_tool,
    rancher_cert_manager_certificates_list,
    rancher_cert_manager_certificates_list_tool,
)
from rancher_mcp.tools.cert_manager._generated_cert_manager_cluster_issuers import (
    rancher_cert_manager_cluster_issuer_get,
    rancher_cert_manager_cluster_issuer_get_tool,
    rancher_cert_manager_cluster_issuer_set_annotations,
    rancher_cert_manager_cluster_issuer_set_annotations_tool,
    rancher_cert_manager_cluster_issuer_set_labels,
    rancher_cert_manager_cluster_issuer_set_labels_tool,
    rancher_cert_manager_cluster_issuers_list,
    rancher_cert_manager_cluster_issuers_list_tool,
)
from rancher_mcp.tools.cert_manager._generated_cert_manager_issuers import (
    rancher_cert_manager_issuer_get,
    rancher_cert_manager_issuer_get_tool,
    rancher_cert_manager_issuer_set_annotations,
    rancher_cert_manager_issuer_set_annotations_tool,
    rancher_cert_manager_issuer_set_labels,
    rancher_cert_manager_issuer_set_labels_tool,
    rancher_cert_manager_issuers_list,
    rancher_cert_manager_issuers_list_tool,
)
from rancher_mcp.tools.support.annotations import IDEMPOTENT_WRITE, READ_ONLY

__all__ = [
    "rancher_cert_manager_certificate_get",
    "rancher_cert_manager_certificate_set_annotations",
    "rancher_cert_manager_certificate_set_labels",
    "rancher_cert_manager_certificates_list",
    "rancher_cert_manager_cluster_issuer_get",
    "rancher_cert_manager_cluster_issuer_set_annotations",
    "rancher_cert_manager_cluster_issuer_set_labels",
    "rancher_cert_manager_cluster_issuers_list",
    "rancher_cert_manager_issuer_get",
    "rancher_cert_manager_issuer_set_annotations",
    "rancher_cert_manager_issuer_set_labels",
    "rancher_cert_manager_issuers_list",
    "register_cert_manager_tools",
]


def register_cert_manager_tools(mcp: FastMCP) -> None:
    """Register curated cert-manager tools with the FastMCP server."""

    mcp.tool(name="rancher_cert_manager_certificates_list", annotations=READ_ONLY)(
        rancher_cert_manager_certificates_list_tool
    )
    mcp.tool(name="rancher_cert_manager_certificate_get", annotations=READ_ONLY)(
        rancher_cert_manager_certificate_get_tool
    )
    mcp.tool(name="rancher_cert_manager_certificate_set_labels", annotations=IDEMPOTENT_WRITE)(
        rancher_cert_manager_certificate_set_labels_tool
    )
    mcp.tool(name="rancher_cert_manager_certificate_set_annotations", annotations=IDEMPOTENT_WRITE)(
        rancher_cert_manager_certificate_set_annotations_tool
    )
    mcp.tool(name="rancher_cert_manager_cluster_issuers_list", annotations=READ_ONLY)(
        rancher_cert_manager_cluster_issuers_list_tool
    )
    mcp.tool(name="rancher_cert_manager_cluster_issuer_get", annotations=READ_ONLY)(
        rancher_cert_manager_cluster_issuer_get_tool
    )
    mcp.tool(name="rancher_cert_manager_cluster_issuer_set_labels", annotations=IDEMPOTENT_WRITE)(
        rancher_cert_manager_cluster_issuer_set_labels_tool
    )
    mcp.tool(
        name="rancher_cert_manager_cluster_issuer_set_annotations", annotations=IDEMPOTENT_WRITE
    )(rancher_cert_manager_cluster_issuer_set_annotations_tool)
    mcp.tool(name="rancher_cert_manager_issuers_list", annotations=READ_ONLY)(
        rancher_cert_manager_issuers_list_tool
    )
    mcp.tool(name="rancher_cert_manager_issuer_get", annotations=READ_ONLY)(
        rancher_cert_manager_issuer_get_tool
    )
    mcp.tool(name="rancher_cert_manager_issuer_set_labels", annotations=IDEMPOTENT_WRITE)(
        rancher_cert_manager_issuer_set_labels_tool
    )
    mcp.tool(name="rancher_cert_manager_issuer_set_annotations", annotations=IDEMPOTENT_WRITE)(
        rancher_cert_manager_issuer_set_annotations_tool
    )
