# This file is generated by scripts/codegen from
# catalog/curated_tools/cert_manager_cluster_issuers.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cert_manager_cluster_issuer tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.cert_manager import (
    RancherCertManagerClusterIssuerDetail,
    RancherCertManagerClusterIssuerList,
)
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.cert_manager.paths import (
    cert_manager_cluster_collection_path,
    cert_manager_cluster_resource_path,
)
from rancher_mcp.tools.cert_manager.shared import (
    build_list_query_params,
    cluster_issuer_summary_from_payload,
    condition_types_true_from_payload,
    items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_cert_manager_cluster_issuers_list(
    instance_name: str,
    cluster_id: str,
    ready: bool | None,
    issuer_kind_used: str | None,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherCertManagerClusterIssuerList:
    """Fetch and normalize cert_manager_cluster_issuers through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        cert_manager_cluster_collection_path(cluster_id, "clusterissuers"),
        params=query_params or None,
    )
    cert_manager_cluster_issuers = [
        cluster_issuer_summary_from_payload(item) for item in items(payload)
    ]
    if ready is not None:
        cert_manager_cluster_issuers = [
            cert_manager_cluster_issuer
            for cert_manager_cluster_issuer in cert_manager_cluster_issuers
            if cert_manager_cluster_issuer.ready is ready
        ]
    if issuer_kind_used is not None:
        cert_manager_cluster_issuers = [
            cert_manager_cluster_issuer
            for cert_manager_cluster_issuer in cert_manager_cluster_issuers
            if cert_manager_cluster_issuer.issuer_kind_used == issuer_kind_used
        ]
    return RancherCertManagerClusterIssuerList(
        instance=instance_name,
        cluster_id=cluster_id,
        cert_manager_cluster_issuer_count=len(cert_manager_cluster_issuers),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        cert_manager_cluster_issuers=cert_manager_cluster_issuers,
        suggested_next_steps=[
            "rancher_cert_manager_cluster_issuer_get",
            "rancher_cert_manager_certificates_list",
        ],
    )


async def rancher_cert_manager_cluster_issuers_list(
    cluster_id: str = "local",
    ready: bool | None = None,
    issuer_kind_used: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertManagerClusterIssuerList:
    """List cert_manager_cluster_issuers with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cert_manager_cluster_issuers_list(
            instance_name,
            cluster_id,
            ready,
            issuer_kind_used,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cert_manager_cluster_issuers_list(
            instance_name,
            cluster_id,
            ready,
            issuer_kind_used,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_cert_manager_cluster_issuer_get(
    instance_name: str,
    cluster_id: str,
    cluster_issuer_name: str,
    client: ManagementDiscoveryClient,
) -> RancherCertManagerClusterIssuerDetail:
    """Fetch and normalize one cert_manager_cluster_issuer."""

    payload = await client.get_json(
        cert_manager_cluster_resource_path(cluster_id, "clusterissuers", cluster_issuer_name)
    )
    summary = cluster_issuer_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherCertManagerClusterIssuerDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ready": summary.ready,
            "issuer_kind_used": summary.issuer_kind_used,
            "annotation_keys": sorted(string_dict(annotations)),
            "condition_types_true": condition_types_true_from_payload(payload),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_cert_manager_cluster_issuers_list",
                "rancher_cert_manager_certificates_list",
            ],
        }
    )


async def rancher_cert_manager_cluster_issuer_get(
    cluster_issuer_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertManagerClusterIssuerDetail:
    """Fetch one cert_manager_cluster_issuer by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cert_manager_cluster_issuer_get(
            instance_name, cluster_id, cluster_issuer_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cert_manager_cluster_issuer_get(
            instance_name,
            cluster_id,
            cluster_issuer_name,
            managed_client,
        )


async def rancher_cert_manager_cluster_issuers_list_tool(
    cluster_id: str = "local",
    ready: bool | None = None,
    issuer_kind_used: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherCertManagerClusterIssuerList:
    """Public MCP wrapper for curated cert_manager_cluster_issuer list."""

    return await rancher_cert_manager_cluster_issuers_list(
        cluster_id=cluster_id,
        ready=ready,
        issuer_kind_used=issuer_kind_used,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_cert_manager_cluster_issuer_get_tool(
    cluster_issuer_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCertManagerClusterIssuerDetail:
    """Public MCP wrapper for curated cert_manager_cluster_issuer detail."""

    return await rancher_cert_manager_cluster_issuer_get(
        cluster_issuer_name=cluster_issuer_name,
        cluster_id=cluster_id,
        instance=instance,
    )
