# This file is generated by scripts/codegen from
# catalog/curated_tools/cert_manager_issuers.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cert_manager_issuer tools."""

from __future__ import annotations

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.cert_manager import (
    RancherCertManagerIssuerDetail,
    RancherCertManagerIssuerList,
)
from rancher_mcp.models.resources import RancherCuratedDeleteResult
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.cert_manager.paths import (
    cert_manager_namespaced_collection_path,
    cert_manager_namespaced_resource_path,
)
from rancher_mcp.tools.cert_manager.shared import (
    build_list_query_params,
    condition_types_true_from_payload,
    issuer_summary_from_payload,
    items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_cert_manager_issuers_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    ready: bool | None,
    issuer_kind_used: str | None,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherCertManagerIssuerList:
    """Fetch and normalize cert_manager_issuers through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        cert_manager_namespaced_collection_path(cluster_id, namespace, "issuers"),
        params=query_params or None,
    )
    cert_manager_issuers = [issuer_summary_from_payload(item) for item in items(payload)]
    if ready is not None:
        cert_manager_issuers = [
            cert_manager_issuer
            for cert_manager_issuer in cert_manager_issuers
            if cert_manager_issuer.ready is ready
        ]
    if issuer_kind_used is not None:
        cert_manager_issuers = [
            cert_manager_issuer
            for cert_manager_issuer in cert_manager_issuers
            if cert_manager_issuer.issuer_kind_used == issuer_kind_used
        ]
    return RancherCertManagerIssuerList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        cert_manager_issuer_count=len(cert_manager_issuers),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        cert_manager_issuers=cert_manager_issuers,
        suggested_next_steps=[
            "rancher_cert_manager_issuer_get",
            "rancher_cert_manager_certificates_list",
        ],
    )


async def rancher_cert_manager_issuers_list(
    namespace: str,
    cluster_id: str = "local",
    ready: bool | None = None,
    issuer_kind_used: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertManagerIssuerList:
    """List cert_manager_issuers in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cert_manager_issuers_list(
            instance_name,
            cluster_id,
            namespace,
            ready,
            issuer_kind_used,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cert_manager_issuers_list(
            instance_name,
            cluster_id,
            namespace,
            ready,
            issuer_kind_used,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_cert_manager_issuer_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    issuer_name: str,
    client: ManagementDiscoveryClient,
) -> RancherCertManagerIssuerDetail:
    """Fetch and normalize one cert_manager_issuer."""

    payload = await client.get_json(
        cert_manager_namespaced_resource_path(cluster_id, namespace, "issuers", issuer_name)
    )
    summary = issuer_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherCertManagerIssuerDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ready": summary.ready,
            "issuer_kind_used": summary.issuer_kind_used,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "condition_types_true": condition_types_true_from_payload(payload),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_cert_manager_issuers_list",
                "rancher_cert_manager_certificates_list",
            ],
        }
    )


async def rancher_cert_manager_issuer_get(
    namespace: str,
    issuer_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertManagerIssuerDetail:
    """Fetch one cert_manager_issuer by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cert_manager_issuer_get(
            instance_name, cluster_id, namespace, issuer_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cert_manager_issuer_get(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            managed_client,
        )


async def _delete_cert_manager_issuer(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    issuer_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one cert_manager_issuer; returns a typed delete result."""

    response_payload = await client.delete_json(
        cert_manager_namespaced_resource_path(cluster_id, namespace, "issuers", issuer_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="cert_manager_issuer",
        resource_name=issuer_name,
        namespace=namespace,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_cert_manager_issuers_list"],
    )


@audit_mutation(operation="cert_manager_issuer_delete", plane="steve")
@rate_limit_writes
async def rancher_cert_manager_issuer_delete(
    namespace: str,
    issuer_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one cert_manager_issuer after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete cert_manager_issuer {issuer_name} in namespace {namespace}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_cert_manager_issuer(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_cert_manager_issuer(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            expected_phrase,
            managed_client,
        )


async def _patch_cert_manager_issuer_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    issuer_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherCertManagerIssuerDetail:
    """Set_labels one cert_manager_issuer via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    payload = await client.patch_json(
        cert_manager_namespaced_resource_path(cluster_id, namespace, "issuers", issuer_name),
        payload=request_payload,
    )
    summary = issuer_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherCertManagerIssuerDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ready": summary.ready,
            "issuer_kind_used": summary.issuer_kind_used,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "condition_types_true": condition_types_true_from_payload(payload),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_cert_manager_issuer_get",
                "rancher_cert_manager_issuers_list",
            ],
        }
    )


@audit_mutation(operation="cert_manager_issuer_set_labels", plane="steve")
@rate_limit_writes
async def rancher_cert_manager_issuer_set_labels(
    namespace: str,
    issuer_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertManagerIssuerDetail:
    """Set_labels one cert_manager_issuer via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_cert_manager_issuer_set_labels(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_cert_manager_issuer_set_labels(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            labels,
            managed_client,
        )


async def _patch_cert_manager_issuer_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    issuer_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherCertManagerIssuerDetail:
    """Set_annotations one cert_manager_issuer via JSON merge-patch; returns the curated detail."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    payload = await client.patch_json(
        cert_manager_namespaced_resource_path(cluster_id, namespace, "issuers", issuer_name),
        payload=request_payload,
    )
    summary = issuer_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherCertManagerIssuerDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "ready": summary.ready,
            "issuer_kind_used": summary.issuer_kind_used,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "condition_types_true": condition_types_true_from_payload(payload),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_cert_manager_issuer_get"],
        }
    )


@audit_mutation(operation="cert_manager_issuer_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_cert_manager_issuer_set_annotations(
    namespace: str,
    issuer_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCertManagerIssuerDetail:
    """Set_annotations one cert_manager_issuer via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_cert_manager_issuer_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_cert_manager_issuer_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            issuer_name,
            annotations,
            managed_client,
        )


async def rancher_cert_manager_issuers_list_tool(
    namespace: str,
    cluster_id: str = "local",
    ready: bool | None = None,
    issuer_kind_used: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherCertManagerIssuerList:
    """Public MCP wrapper for curated cert_manager_issuer list."""

    return await rancher_cert_manager_issuers_list(
        namespace=namespace,
        cluster_id=cluster_id,
        ready=ready,
        issuer_kind_used=issuer_kind_used,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_cert_manager_issuer_get_tool(
    namespace: str,
    issuer_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCertManagerIssuerDetail:
    """Public MCP wrapper for curated cert_manager_issuer detail."""

    return await rancher_cert_manager_issuer_get(
        namespace=namespace,
        issuer_name=issuer_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cert_manager_issuer_delete_tool(
    namespace: str,
    issuer_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Public MCP wrapper for curated cert_manager_issuer delete."""

    return await rancher_cert_manager_issuer_delete(
        namespace=namespace,
        issuer_name=issuer_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cert_manager_issuer_set_labels_tool(
    namespace: str,
    issuer_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCertManagerIssuerDetail:
    """Public MCP wrapper for curated cert_manager_issuer set_labels."""

    return await rancher_cert_manager_issuer_set_labels(
        namespace=namespace,
        issuer_name=issuer_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_cert_manager_issuer_set_annotations_tool(
    namespace: str,
    issuer_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCertManagerIssuerDetail:
    """Public MCP wrapper for curated cert_manager_issuer set_annotations."""

    return await rancher_cert_manager_issuer_set_annotations(
        namespace=namespace,
        issuer_name=issuer_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
