# This file is generated by scripts/codegen from
# catalog/curated_tools/jobs.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher job tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.batch_workloads import RancherJobDetail, RancherJobList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.batch_workloads.paths import batch_v1_collection_path, batch_v1_resource_path
from rancher_mcp.tools.batch_workloads.shared import (
    build_list_query_params,
    container_images_from_template,
    items,
    job_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_jobs_list(
    instance_name: str,
    cluster_id: str,
    namespace: str | None,
    complete: bool | None,
    failed_terminal: bool | None,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherJobList:
    """Fetch and normalize jobs through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        batch_v1_collection_path(cluster_id, namespace, "jobs"),
        params=query_params or None,
    )
    jobs = [job_summary_from_payload(item) for item in items(payload)]
    if complete is not None:
        jobs = [job for job in jobs if job.complete is complete]
    if failed_terminal is not None:
        jobs = [job for job in jobs if job.failed_terminal is failed_terminal]
    return RancherJobList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        job_count=len(jobs),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        jobs=jobs,
        suggested_next_steps=[
            "rancher_job_get",
            "rancher_pods_list",
        ],
    )


async def rancher_jobs_list(
    namespace: str | None = None,
    cluster_id: str = "local",
    complete: bool | None = None,
    failed_terminal: bool | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherJobList:
    """List jobs with typed summaries — in one namespace, or cluster-wide when namespace is omitted."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_jobs_list(
            instance_name,
            cluster_id,
            namespace,
            complete,
            failed_terminal,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_jobs_list(
            instance_name,
            cluster_id,
            namespace,
            complete,
            failed_terminal,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_job_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    job_name: str,
    client: ManagementDiscoveryClient,
) -> RancherJobDetail:
    """Fetch and normalize one job."""

    payload = await client.get_json(batch_v1_resource_path(cluster_id, namespace, "jobs", job_name))
    summary = job_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherJobDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "complete": summary.complete,
            "failed_terminal": summary.failed_terminal,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "container_images": container_images_from_template(payload),
            "payload": dict(payload),
            "cluster_id": cluster_id,
            "suggested_next_steps": ["rancher_jobs_list", "rancher_pods_list"],
        }
    )


async def rancher_job_get(
    namespace: str,
    job_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherJobDetail:
    """Fetch one job by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_job_get(instance_name, cluster_id, namespace, job_name, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_job_get(
            instance_name,
            cluster_id,
            namespace,
            job_name,
            managed_client,
        )


async def rancher_jobs_list_tool(
    namespace: str | None = None,
    cluster_id: str = "local",
    complete: bool | None = None,
    failed_terminal: bool | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherJobList:
    """List jobs as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool. Omit `namespace` to list across the whole cluster; pass it to scope to one namespace."""

    return await rancher_jobs_list(
        namespace=namespace,
        cluster_id=cluster_id,
        complete=complete,
        failed_terminal=failed_terminal,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_job_get_tool(
    namespace: str,
    job_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherJobDetail:
    """Fetch one job and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_job_get(
        namespace=namespace,
        job_name=job_name,
        cluster_id=cluster_id,
        instance=instance,
    )
