# This file is generated by scripts/codegen from
# catalog/curated_tools/priority_classes.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher priority_class tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.scheduling import RancherPriorityClassDetail, RancherPriorityClassList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.scheduling.paths import (
    scheduling_v1_collection_path,
    scheduling_v1_resource_path,
)
from rancher_mcp.tools.scheduling.shared import (
    build_list_query_params,
    items,
    priority_class_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_priority_classes_list(
    instance_name: str,
    cluster_id: str,
    global_default: bool | None,
    preemption_policy: str | None,
    limit: int | None,
    label_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherPriorityClassList:
    """Fetch and normalize priority_classes through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
    )
    payload = await client.get_json(
        scheduling_v1_collection_path(cluster_id, "priorityclasses"),
        params=query_params or None,
    )
    priority_classes = [priority_class_summary_from_payload(item) for item in items(payload)]
    if global_default is not None:
        priority_classes = [
            priority_class
            for priority_class in priority_classes
            if priority_class.global_default is global_default
        ]
    if preemption_policy is not None:
        priority_classes = [
            priority_class
            for priority_class in priority_classes
            if priority_class.preemption_policy == preemption_policy
        ]
    return RancherPriorityClassList(
        instance=instance_name,
        cluster_id=cluster_id,
        priority_class_count=len(priority_classes),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        priority_classes=priority_classes,
        suggested_next_steps=[
            "rancher_priority_class_get",
            "rancher_pods_list",
        ],
    )


async def rancher_priority_classes_list(
    cluster_id: str = "local",
    global_default: bool | None = None,
    preemption_policy: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherPriorityClassList:
    """List priority_classes with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_priority_classes_list(
            instance_name,
            cluster_id,
            global_default,
            preemption_policy,
            limit,
            label_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_priority_classes_list(
            instance_name,
            cluster_id,
            global_default,
            preemption_policy,
            limit,
            label_selector,
            managed_client,
            page_token,
        )


async def _fetch_priority_class_get(
    instance_name: str,
    cluster_id: str,
    priority_class_name: str,
    client: ManagementDiscoveryClient,
) -> RancherPriorityClassDetail:
    """Fetch and normalize one priority_class."""

    payload = await client.get_json(
        scheduling_v1_resource_path(cluster_id, "priorityclasses", priority_class_name)
    )
    summary = priority_class_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherPriorityClassDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "value": summary.value,
            "description": summary.description,
            "annotation_keys": sorted(string_dict(annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_priority_classes_list", "rancher_pods_list"],
        }
    )


async def rancher_priority_class_get(
    priority_class_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherPriorityClassDetail:
    """Fetch one priority_class by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_priority_class_get(
            instance_name, cluster_id, priority_class_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_priority_class_get(
            instance_name,
            cluster_id,
            priority_class_name,
            managed_client,
        )


async def rancher_priority_classes_list_tool(
    cluster_id: str = "local",
    global_default: bool | None = None,
    preemption_policy: str | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherPriorityClassList:
    """Public MCP wrapper for curated priority_class list."""

    return await rancher_priority_classes_list(
        cluster_id=cluster_id,
        global_default=global_default,
        preemption_policy=preemption_policy,
        limit=limit,
        label_selector=label_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_priority_class_get_tool(
    priority_class_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherPriorityClassDetail:
    """Public MCP wrapper for curated priority_class detail."""

    return await rancher_priority_class_get(
        priority_class_name=priority_class_name,
        cluster_id=cluster_id,
        instance=instance,
    )
