# This file is generated by scripts/codegen from
# catalog/curated_tools/node_drivers.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher node_driver tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.provisioning import RancherNodeDriverDetail, RancherNodeDriverList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.provisioning.shared import (
    build_driver_query_params,
    data_items,
    node_driver_summary_from_payload,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_node_drivers_list(
    instance_name: str,
    limit: int | None,
    active: bool | None,
    name: str | None,
    state: str | None,
    sort_by: str | None,
    reverse: bool | None,
    client: ManagementDiscoveryClient,
) -> RancherNodeDriverList:
    """Fetch and normalize the Rancher node_drivers collection."""

    query_params = build_driver_query_params(
        limit=limit,
        active=active,
        name=name,
        state=state,
        sort_by=sort_by,
        reverse=reverse,
    )
    payload = await client.get_json("/v3/nodedrivers", params=query_params or None)
    node_drivers = [node_driver_summary_from_payload(item) for item in data_items(payload)]
    return RancherNodeDriverList(
        instance=instance_name,
        node_driver_count=len(node_drivers),
        applied_query_params=query_params,
        node_drivers=node_drivers,
        suggested_next_steps=[
            "rancher_node_driver_get",
            "rancher_node_templates_list",
        ],
    )


async def rancher_node_drivers_list(
    limit: int | None = None,
    active: bool | None = None,
    name: str | None = None,
    state: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNodeDriverList:
    """List node_drivers with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_node_drivers_list(
            instance_name,
            limit,
            active,
            name,
            state,
            sort_by,
            reverse,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_node_drivers_list(
            instance_name,
            limit,
            active,
            name,
            state,
            sort_by,
            reverse,
            managed_client,
        )


async def _fetch_node_driver_get(
    instance_name: str,
    driver_id: str,
    client: ManagementDiscoveryClient,
) -> RancherNodeDriverDetail:
    """Fetch and normalize one node_driver."""

    payload = await client.get_json(f"/v3/nodedrivers/{driver_id}")

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherNodeDriverDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "annotation_keys": sorted(string_dict(annotations)),
            "action_keys": sorted(mapping_value(payload, "actions") or {}),
            "link_keys": sorted(mapping_value(payload, "links") or {}),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_node_drivers_list", "rancher_node_templates_list"],
        }
    )


async def rancher_node_driver_get(
    driver_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherNodeDriverDetail:
    """Fetch one node_driver by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_node_driver_get(instance_name, driver_id, client)
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_node_driver_get(
            instance_name,
            driver_id,
            managed_client,
        )


async def rancher_node_drivers_list_tool(
    limit: int | None = None,
    active: bool | None = None,
    name: str | None = None,
    state: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
) -> RancherNodeDriverList:
    """List node_drivers as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_node_drivers_list(
        limit=limit,
        active=active,
        name=name,
        state=state,
        sort_by=sort_by,
        reverse=reverse,
        instance=instance,
    )


async def rancher_node_driver_get_tool(
    driver_id: str,
    instance: str | None = None,
) -> RancherNodeDriverDetail:
    """Fetch one node_driver and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_node_driver_get(
        driver_id=driver_id,
        instance=instance,
    )
