# This file is generated by scripts/codegen from
# catalog/curated_tools/project_role_template_bindings.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher project_role_template_binding tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.rbac import (
    RancherProjectRoleTemplateBindingDetail,
    RancherProjectRoleTemplateBindingList,
)
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.rbac.shared import (
    binding_subject,
    build_project_role_template_binding_query_params,
    data_items,
    link_keys,
    project_role_template_binding_summary_from_payload,
)


async def _fetch_project_role_template_bindings_list(
    instance_name: str,
    limit: int | None,
    project_id: str | None,
    role_template_id: str | None,
    user_id: str | None,
    user_principal_id: str | None,
    group_id: str | None,
    group_principal_id: str | None,
    namespace_id: str | None,
    service_account: str | None,
    name: str | None,
    sort_by: str | None,
    reverse: bool | None,
    client: ManagementDiscoveryClient,
) -> RancherProjectRoleTemplateBindingList:
    """Fetch and normalize the Rancher project_role_template_bindings collection."""

    query_params = build_project_role_template_binding_query_params(
        limit=limit,
        project_id=project_id,
        role_template_id=role_template_id,
        user_id=user_id,
        user_principal_id=user_principal_id,
        group_id=group_id,
        group_principal_id=group_principal_id,
        namespace_id=namespace_id,
        service_account=service_account,
        name=name,
        sort_by=sort_by,
        reverse=reverse,
    )
    payload = await client.get_json("/v3/projectroletemplatebindings", params=query_params or None)
    project_role_template_bindings = [
        project_role_template_binding_summary_from_payload(item) for item in data_items(payload)
    ]
    return RancherProjectRoleTemplateBindingList(
        instance=instance_name,
        project_role_template_binding_count=len(project_role_template_bindings),
        applied_query_params=query_params,
        project_role_template_bindings=project_role_template_bindings,
        suggested_next_steps=[
            "rancher_project_role_template_binding_get",
            "rancher_role_templates_list",
        ],
    )


async def rancher_project_role_template_bindings_list(
    limit: int | None = None,
    project_id: str | None = None,
    role_template_id: str | None = None,
    user_id: str | None = None,
    user_principal_id: str | None = None,
    group_id: str | None = None,
    group_principal_id: str | None = None,
    namespace_id: str | None = None,
    service_account: str | None = None,
    name: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherProjectRoleTemplateBindingList:
    """List project_role_template_bindings with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_project_role_template_bindings_list(
            instance_name,
            limit,
            project_id,
            role_template_id,
            user_id,
            user_principal_id,
            group_id,
            group_principal_id,
            namespace_id,
            service_account,
            name,
            sort_by,
            reverse,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_project_role_template_bindings_list(
            instance_name,
            limit,
            project_id,
            role_template_id,
            user_id,
            user_principal_id,
            group_id,
            group_principal_id,
            namespace_id,
            service_account,
            name,
            sort_by,
            reverse,
            managed_client,
        )


async def _fetch_project_role_template_binding_get(
    instance_name: str,
    project_role_template_binding_id: str,
    client: ManagementDiscoveryClient,
) -> RancherProjectRoleTemplateBindingDetail:
    """Fetch and normalize one project_role_template_binding."""

    payload = await client.get_json(
        f"/v3/projectroletemplatebindings/{project_role_template_binding_id}"
    )

    subject = binding_subject(payload)
    detail = RancherProjectRoleTemplateBindingDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "subject_kind": subject[0],
            "subject_id": subject[1],
            "link_keys": link_keys(payload),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_project_role_template_bindings_list",
                "rancher_role_templates_list",
            ],
        }
    )


async def rancher_project_role_template_binding_get(
    project_role_template_binding_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherProjectRoleTemplateBindingDetail:
    """Fetch one project_role_template_binding by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_project_role_template_binding_get(
            instance_name, project_role_template_binding_id, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_project_role_template_binding_get(
            instance_name,
            project_role_template_binding_id,
            managed_client,
        )


async def rancher_project_role_template_bindings_list_tool(
    limit: int | None = None,
    project_id: str | None = None,
    role_template_id: str | None = None,
    user_id: str | None = None,
    user_principal_id: str | None = None,
    group_id: str | None = None,
    group_principal_id: str | None = None,
    namespace_id: str | None = None,
    service_account: str | None = None,
    name: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
) -> RancherProjectRoleTemplateBindingList:
    """Public MCP wrapper for curated project_role_template_binding list."""

    return await rancher_project_role_template_bindings_list(
        limit=limit,
        project_id=project_id,
        role_template_id=role_template_id,
        user_id=user_id,
        user_principal_id=user_principal_id,
        group_id=group_id,
        group_principal_id=group_principal_id,
        namespace_id=namespace_id,
        service_account=service_account,
        name=name,
        sort_by=sort_by,
        reverse=reverse,
        instance=instance,
    )


async def rancher_project_role_template_binding_get_tool(
    project_role_template_binding_id: str,
    instance: str | None = None,
) -> RancherProjectRoleTemplateBindingDetail:
    """Public MCP wrapper for curated project_role_template_binding detail."""

    return await rancher_project_role_template_binding_get(
        project_role_template_binding_id=project_role_template_binding_id,
        instance=instance,
    )
