# This file is generated by scripts/codegen from
# catalog/curated_tools/cluster_role_template_bindings.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher cluster_role_template_binding tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.rbac import (
    RancherClusterRoleTemplateBindingDetail,
    RancherClusterRoleTemplateBindingList,
)
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.tools.rbac.shared import (
    binding_subject,
    build_cluster_role_template_binding_query_params,
    cluster_role_template_binding_summary_from_payload,
    data_items,
    link_keys,
)


async def _fetch_cluster_role_template_bindings_list(
    instance_name: str,
    limit: int | None,
    cluster_id: str | None,
    role_template_id: str | None,
    user_id: str | None,
    user_principal_id: str | None,
    group_id: str | None,
    group_principal_id: str | None,
    namespace_id: str | None,
    name: str | None,
    sort_by: str | None,
    reverse: bool | None,
    client: ManagementDiscoveryClient,
) -> RancherClusterRoleTemplateBindingList:
    """Fetch and normalize the Rancher cluster_role_template_bindings collection."""

    query_params = build_cluster_role_template_binding_query_params(
        limit=limit,
        cluster_id=cluster_id,
        role_template_id=role_template_id,
        user_id=user_id,
        user_principal_id=user_principal_id,
        group_id=group_id,
        group_principal_id=group_principal_id,
        namespace_id=namespace_id,
        name=name,
        sort_by=sort_by,
        reverse=reverse,
    )
    payload = await client.get_json("/v3/clusterroletemplatebindings", params=query_params or None)
    cluster_role_template_bindings = [
        cluster_role_template_binding_summary_from_payload(item) for item in data_items(payload)
    ]
    return RancherClusterRoleTemplateBindingList(
        instance=instance_name,
        cluster_id=cluster_id,
        cluster_role_template_binding_count=len(cluster_role_template_bindings),
        applied_query_params=query_params,
        cluster_role_template_bindings=cluster_role_template_bindings,
        suggested_next_steps=[
            "rancher_cluster_role_template_binding_get",
            "rancher_role_templates_list",
        ],
    )


async def rancher_cluster_role_template_bindings_list(
    limit: int | None = None,
    cluster_id: str | None = None,
    role_template_id: str | None = None,
    user_id: str | None = None,
    user_principal_id: str | None = None,
    group_id: str | None = None,
    group_principal_id: str | None = None,
    namespace_id: str | None = None,
    name: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherClusterRoleTemplateBindingList:
    """List cluster_role_template_bindings with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_role_template_bindings_list(
            instance_name,
            limit,
            cluster_id,
            role_template_id,
            user_id,
            user_principal_id,
            group_id,
            group_principal_id,
            namespace_id,
            name,
            sort_by,
            reverse,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_role_template_bindings_list(
            instance_name,
            limit,
            cluster_id,
            role_template_id,
            user_id,
            user_principal_id,
            group_id,
            group_principal_id,
            namespace_id,
            name,
            sort_by,
            reverse,
            managed_client,
        )


async def _fetch_cluster_role_template_binding_get(
    instance_name: str,
    cluster_role_template_binding_id: str,
    client: ManagementDiscoveryClient,
) -> RancherClusterRoleTemplateBindingDetail:
    """Fetch and normalize one cluster_role_template_binding."""

    payload = await client.get_json(
        f"/v3/clusterroletemplatebindings/{cluster_role_template_binding_id}"
    )

    subject = binding_subject(payload)
    detail = RancherClusterRoleTemplateBindingDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "subject_kind": subject[0],
            "subject_id": subject[1],
            "link_keys": link_keys(payload),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_cluster_role_template_bindings_list",
                "rancher_role_templates_list",
            ],
        }
    )


async def rancher_cluster_role_template_binding_get(
    cluster_role_template_binding_id: str,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherClusterRoleTemplateBindingDetail:
    """Fetch one cluster_role_template_binding by name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_cluster_role_template_binding_get(
            instance_name, cluster_role_template_binding_id, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_cluster_role_template_binding_get(
            instance_name,
            cluster_role_template_binding_id,
            managed_client,
        )


async def rancher_cluster_role_template_bindings_list_tool(
    limit: int | None = None,
    cluster_id: str | None = None,
    role_template_id: str | None = None,
    user_id: str | None = None,
    user_principal_id: str | None = None,
    group_id: str | None = None,
    group_principal_id: str | None = None,
    namespace_id: str | None = None,
    name: str | None = None,
    sort_by: str | None = None,
    reverse: bool | None = None,
    instance: str | None = None,
) -> RancherClusterRoleTemplateBindingList:
    """List cluster_role_template_bindings as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_cluster_role_template_bindings_list(
        limit=limit,
        cluster_id=cluster_id,
        role_template_id=role_template_id,
        user_id=user_id,
        user_principal_id=user_principal_id,
        group_id=group_id,
        group_principal_id=group_principal_id,
        namespace_id=namespace_id,
        name=name,
        sort_by=sort_by,
        reverse=reverse,
        instance=instance,
    )


async def rancher_cluster_role_template_binding_get_tool(
    cluster_role_template_binding_id: str,
    instance: str | None = None,
) -> RancherClusterRoleTemplateBindingDetail:
    """Fetch one cluster_role_template_binding and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_cluster_role_template_binding_get(
        cluster_role_template_binding_id=cluster_role_template_binding_id,
        instance=instance,
    )
