"""Generate ``docs/tool-manifest.json`` from the live FastMCP tool registry.

The manifest is the machine-readable, always-current tool catalog: one
entry per registered MCP tool with its description, safety annotations,
and input parameters. It is GENERATED — the FastMCP registry inside
``create_mcp_server()`` is the single source of truth, so the committed
file can never silently drift from the code (``--check`` regenerates in
memory and fails when it does; wired into ``make validate``).

The server is instantiated offline: tool registration contacts no live
Rancher, so placeholder credentials in the environment are enough.

Usage::

    uv run python scripts/generate_tool_manifest.py           # write
    uv run python scripts/generate_tool_manifest.py --check   # CI gate

Exit codes: 0 ok / 1 stale manifest (--check) / 2 generation error.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "docs" / "tool-manifest.json"


def build_manifest() -> dict[str, Any]:
    """Instantiate the server offline and dump its tool registry."""
    # Placeholder credentials so AppSettings resolves without a real
    # Rancher; registration never dials out. setdefault keeps any real
    # env (or .env) working unchanged.
    os.environ.setdefault("RANCHER_URL", "https://rancher.invalid")
    os.environ.setdefault("RANCHER_TOKEN", "token-manifest:offline")  # pragma: allowlist secret

    from rancher_mcp.server import create_mcp_server

    mcp = create_mcp_server()
    tools = asyncio.run(mcp.list_tools())

    entries: list[dict[str, Any]] = []
    for tool in sorted(tools, key=lambda t: t.name):
        ann = tool.annotations
        schema: dict[str, Any] = tool.inputSchema or {}
        properties: dict[str, Any] = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        entries.append(
            {
                "name": tool.name,
                "description": (tool.description or "").strip(),
                "read_only": None if ann is None else ann.readOnlyHint,
                "destructive": None if ann is None else ann.destructiveHint,
                "idempotent": None if ann is None else ann.idempotentHint,
                "params": [
                    {"name": name, "required": name in required} for name in sorted(properties)
                ],
            }
        )

    return {
        "_generated": (
            "GENERATED by scripts/generate_tool_manifest.py — do not edit. "
            "Regenerate: make tool-manifest"
        ),
        "tool_count": len(entries),
        "read_only_count": sum(1 for e in entries if e["read_only"] is True),
        "write_count": sum(1 for e in entries if e["read_only"] is False),
        "destructive_count": sum(1 for e in entries if e["destructive"] is True),
        "tools": entries,
    }


def render(manifest: dict[str, Any]) -> str:
    """Stable, human-diffable JSON serialization."""
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or verify docs/tool-manifest.json.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed manifest matches the live registry (no write)",
    )
    args = parser.parse_args()

    try:
        manifest = build_manifest()
    except Exception as exc:  # noqa: BLE001 — gate must report, not crash silently
        sys.stderr.write(f"generate_tool_manifest: cannot build server registry: {exc}\n")
        return 2

    if args.check:
        if not MANIFEST_PATH.is_file():
            sys.stderr.write(
                "generate_tool_manifest: docs/tool-manifest.json is missing. "
                "Run `make tool-manifest` and commit it.\n"
            )
            return 1
        committed = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        if committed != manifest:
            sys.stderr.write(
                "generate_tool_manifest: docs/tool-manifest.json is STALE — the tool "
                "registry changed. Run `make tool-manifest` and commit the result.\n"
            )
            return 1
        print(f"tool-manifest check ok: {manifest['tool_count']} tools, manifest current.")
        return 0

    MANIFEST_PATH.write_text(render(manifest), encoding="utf-8")
    print(
        f"wrote {MANIFEST_PATH.relative_to(REPO_ROOT)}: {manifest['tool_count']} tools "
        f"({manifest['read_only_count']} read-only, {manifest['write_count']} writes, "
        f"{manifest['destructive_count']} destructive)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
