"""Repo-managed local Rancher compatibility labs."""

# This package __init__ is a pure re-export shim. It deliberately re-exports a
# few leading-underscore helpers (_parse_int_env, _download_bytes,
# _download_text) that the test suite reaches through the package namespace, so
# reportPrivateUsage is disabled for these intentional re-exports only.
# pyright: reportPrivateUsage=false

from __future__ import annotations

from .agent import (
    cleanup_stale_downstream_credentials,
    converge_downstream_agent_registration,
    downstream_agent_env_value,
    ensure_imported_downstream_cluster_up,
    reconcile_downstream_agent_resources,
    wait_for_downstream_agent_deployment,
    wait_for_imported_cluster_ready,
)
from .cli import DEFAULT_REPO_ROOT, build_parser, ensure_lab_up, main, reset_lab
from .imported import (
    downstream_agent_ca_checksum,
    ensure_imported_cluster_resource,
    fetch_import_manifest,
    get_cluster_condition,
    get_rancher_setting,
    imported_cluster_is_ready,
    patch_import_manifest,
    patch_rancher_setting,
    prewarm_agent_host_certificate,
    refresh_cluster_registration_token,
    sync_rancher_cacerts,
)
from .kind import (
    _download_bytes,
    _download_text,
    build_kind_create_command,
    ensure_kind_binary,
    ensure_kind_cluster_down,
    ensure_kind_cluster_up,
    ensure_kind_down,
    ensure_kind_up,
    kind_checksum_url,
    kind_cluster_exists,
    kind_download_url,
    platform_suffix,
    render_kind_config,
)
from .models import ClusterSpec, LabConfig, LabPaths, _parse_int_env
from .process import (
    command_exists,
    ensure_docker_available,
    ensure_helm_available,
    ensure_helm_repos,
    ensure_kubectl_available,
    ensure_lab_directories,
    ensure_namespace,
    helm_args,
    kubectl_args,
    kubectl_json,
    rollout_status,
    run_command,
    run_curl,
    wait_for_rollout,
)
from .profiles import PROFILE_DEFAULTS, LabProfile, profile_env_name, profiles_for
from .rancher import (
    build_port_forward_supervisor_command,
    ensure_cert_manager_up,
    ensure_port_forward,
    ensure_rancher_chart_down,
    ensure_rancher_chart_up,
    port_forward_running,
    stop_port_forward,
    wait_for_rancher_port_forward,
)
from .status import (
    collect_cluster_status,
    collect_status,
    print_cluster_nodes,
    print_rancher_logs,
    print_status,
)

__all__ = [
    "DEFAULT_REPO_ROOT",
    "ClusterSpec",
    "LabConfig",
    "LabProfile",
    "LabPaths",
    "PROFILE_DEFAULTS",
    "_download_bytes",
    "_download_text",
    "_parse_int_env",
    "build_kind_create_command",
    "build_parser",
    "build_port_forward_supervisor_command",
    "cleanup_stale_downstream_credentials",
    "collect_cluster_status",
    "collect_status",
    "command_exists",
    "converge_downstream_agent_registration",
    "downstream_agent_ca_checksum",
    "downstream_agent_env_value",
    "ensure_cert_manager_up",
    "ensure_docker_available",
    "ensure_helm_available",
    "ensure_helm_repos",
    "ensure_imported_cluster_resource",
    "ensure_imported_downstream_cluster_up",
    "ensure_kind_binary",
    "ensure_kind_cluster_down",
    "ensure_kind_cluster_up",
    "ensure_kind_down",
    "ensure_kind_up",
    "ensure_kubectl_available",
    "ensure_lab_directories",
    "ensure_lab_up",
    "ensure_namespace",
    "ensure_port_forward",
    "ensure_rancher_chart_down",
    "ensure_rancher_chart_up",
    "fetch_import_manifest",
    "get_cluster_condition",
    "get_rancher_setting",
    "helm_args",
    "imported_cluster_is_ready",
    "kind_checksum_url",
    "kind_cluster_exists",
    "kind_download_url",
    "kubectl_args",
    "kubectl_json",
    "main",
    "patch_import_manifest",
    "patch_rancher_setting",
    "platform_suffix",
    "profile_env_name",
    "profiles_for",
    "port_forward_running",
    "prewarm_agent_host_certificate",
    "print_cluster_nodes",
    "print_rancher_logs",
    "print_status",
    "reconcile_downstream_agent_resources",
    "refresh_cluster_registration_token",
    "render_kind_config",
    "reset_lab",
    "rollout_status",
    "run_command",
    "run_curl",
    "stop_port_forward",
    "sync_rancher_cacerts",
    "wait_for_downstream_agent_deployment",
    "wait_for_imported_cluster_ready",
    "wait_for_rancher_port_forward",
    "wait_for_rollout",
]
