# This file is generated by scripts/codegen from
# catalog/curated_tools/daemonsets.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher daemonset tools."""

from __future__ import annotations

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.resources import RancherCuratedDeleteResult, RancherMutationReceipt
from rancher_mcp.models.workloads import RancherDaemonSetDetail, RancherDaemonSetList
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resource_queries import build_steve_list_query_params
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.support.values import mapping_value, string_dict
from rancher_mcp.tools.workloads.paths import workload_collection_path, workload_resource_path
from rancher_mcp.tools.workloads.shared import (
    daemonset_summary_from_payload,
    items,
)


async def _fetch_daemonsets_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    ready: bool | None,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherDaemonSetList:
    """Fetch and normalize daemonsets through Rancher's raw Kubernetes proxy."""

    query_params = build_steve_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        workload_collection_path(cluster_id, namespace, "daemonsets"),
        params=query_params or None,
    )
    daemonsets = [daemonset_summary_from_payload(item) for item in items(payload)]
    if ready is not None:
        daemonsets = [daemonset for daemonset in daemonsets if daemonset.ready is ready]
    return RancherDaemonSetList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        daemonset_count=len(daemonsets),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        daemonsets=daemonsets,
        suggested_next_steps=[
            "rancher_daemonset_get",
            "rancher_pods_list",
        ],
    )


async def rancher_daemonsets_list(
    namespace: str,
    cluster_id: str = "local",
    ready: bool | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherDaemonSetList:
    """List daemonsets in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_daemonsets_list(
            instance_name,
            cluster_id,
            namespace,
            ready,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_daemonsets_list(
            instance_name,
            cluster_id,
            namespace,
            ready,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_daemonset_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    daemonset_name: str,
    client: ManagementDiscoveryClient,
) -> RancherDaemonSetDetail:
    """Fetch and normalize one daemonset."""

    payload = await client.get_json(
        workload_resource_path(cluster_id, namespace, "daemonsets", daemonset_name)
    )
    summary = daemonset_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherDaemonSetDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "id": summary.id,
            "ready": summary.ready,
            "container_images": summary.container_images,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_daemonsets_list", "rancher_pods_list"],
        }
    )


async def rancher_daemonset_get(
    namespace: str,
    daemonset_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherDaemonSetDetail:
    """Fetch one daemonset by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_daemonset_get(
            instance_name, cluster_id, namespace, daemonset_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_daemonset_get(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            managed_client,
        )


async def _delete_daemonset(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    daemonset_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one daemonset; returns a typed delete result."""

    response_payload = await client.delete_json(
        workload_resource_path(cluster_id, namespace, "daemonsets", daemonset_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="daemonset",
        resource_name=daemonset_name,
        namespace=namespace,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_daemonsets_list"],
    )


@audit_mutation(operation="daemonset_delete", plane="steve")
@rate_limit_writes
async def rancher_daemonset_delete(
    namespace: str,
    daemonset_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one daemonset after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete daemonset {daemonset_name} in namespace {namespace}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_daemonset(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_daemonset(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            expected_phrase,
            managed_client,
        )


async def _patch_daemonset_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    daemonset_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_labels one daemonset via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "daemonsets", daemonset_name),
        payload=request_payload,
    )
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="daemonset",
        name=daemonset_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
    )


@audit_mutation(operation="daemonset_set_labels", plane="steve")
@rate_limit_writes
async def rancher_daemonset_set_labels(
    namespace: str,
    daemonset_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one daemonset via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_daemonset_set_labels(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_daemonset_set_labels(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            labels,
            managed_client,
        )


async def _patch_daemonset_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    daemonset_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_annotations one daemonset via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "daemonsets", daemonset_name),
        payload=request_payload,
    )
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="daemonset",
        name=daemonset_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
    )


@audit_mutation(operation="daemonset_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_daemonset_set_annotations(
    namespace: str,
    daemonset_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one daemonset via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_daemonset_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_daemonset_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            daemonset_name,
            annotations,
            managed_client,
        )


async def rancher_daemonsets_list_tool(
    namespace: str,
    cluster_id: str = "local",
    ready: bool | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherDaemonSetList:
    """Public MCP wrapper for curated daemonset list."""

    return await rancher_daemonsets_list(
        namespace=namespace,
        cluster_id=cluster_id,
        ready=ready,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_daemonset_get_tool(
    namespace: str,
    daemonset_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherDaemonSetDetail:
    """Public MCP wrapper for curated daemonset detail."""

    return await rancher_daemonset_get(
        namespace=namespace,
        daemonset_name=daemonset_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_daemonset_delete_tool(
    namespace: str,
    daemonset_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Public MCP wrapper for curated daemonset delete."""

    return await rancher_daemonset_delete(
        namespace=namespace,
        daemonset_name=daemonset_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_daemonset_set_labels_tool(
    namespace: str,
    daemonset_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Public MCP wrapper for curated daemonset set_labels."""

    return await rancher_daemonset_set_labels(
        namespace=namespace,
        daemonset_name=daemonset_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_daemonset_set_annotations_tool(
    namespace: str,
    daemonset_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Public MCP wrapper for curated daemonset set_annotations."""

    return await rancher_daemonset_set_annotations(
        namespace=namespace,
        daemonset_name=daemonset_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )
