# This file is generated by scripts/codegen from
# catalog/curated_tools/deployments.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher deployment tools."""

from __future__ import annotations

import time

from rancher_mcp.audit import audit_mutation
from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.exceptions import RancherCapabilityError
from rancher_mcp.models.resources import RancherCuratedDeleteResult, RancherMutationReceipt
from rancher_mcp.models.workloads import RancherDeploymentDetail, RancherDeploymentList
from rancher_mcp.rate_limit import rate_limit_writes
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resource_queries import build_steve_list_query_params
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.services.safety import ensure_instance_writable
from rancher_mcp.tools.support.mutations import fetch_patch_before
from rancher_mcp.tools.support.values import mapping_value, string_dict
from rancher_mcp.tools.workloads.paths import workload_collection_path, workload_resource_path
from rancher_mcp.tools.workloads.shared import (
    deployment_summary_from_payload,
    items,
)


async def _fetch_deployments_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    ready: bool | None,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherDeploymentList:
    """Fetch and normalize deployments through Rancher's raw Kubernetes proxy."""

    query_params = build_steve_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        workload_collection_path(cluster_id, namespace, "deployments"),
        params=query_params or None,
    )
    deployments = [deployment_summary_from_payload(item) for item in items(payload)]
    if ready is not None:
        deployments = [deployment for deployment in deployments if deployment.ready is ready]
    return RancherDeploymentList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        deployment_count=len(deployments),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        deployments=deployments,
        suggested_next_steps=[
            "rancher_deployment_get",
            "rancher_pods_list",
            "rancher_workload_readiness",
        ],
    )


async def rancher_deployments_list(
    namespace: str,
    cluster_id: str = "local",
    ready: bool | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherDeploymentList:
    """List deployments in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_deployments_list(
            instance_name,
            cluster_id,
            namespace,
            ready,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_deployments_list(
            instance_name,
            cluster_id,
            namespace,
            ready,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_deployment_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    client: ManagementDiscoveryClient,
) -> RancherDeploymentDetail:
    """Fetch and normalize one deployment."""

    payload = await client.get_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
    )
    summary = deployment_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    metadata_annotations = mapping_value(metadata, "annotations") or {}
    detail = RancherDeploymentDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "id": summary.id,
            "ready": summary.ready,
            "rollout_complete": summary.rollout_complete,
            "container_images": summary.container_images,
            "reason": summary.reason,
            "since": summary.since,
            "annotation_keys": sorted(string_dict(metadata_annotations)),
            "payload": dict(payload),
            "suggested_next_steps": [
                "rancher_deployments_list",
                "rancher_pods_list",
                "rancher_workload_readiness",
            ],
        }
    )


async def rancher_deployment_get(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherDeploymentDetail:
    """Fetch one deployment by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_deployment_get(
            instance_name, cluster_id, namespace, deployment_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_deployment_get(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            managed_client,
        )


async def _delete_deployment(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    confirmation_phrase_used: str,
    client: ManagementDiscoveryClient,
) -> RancherCuratedDeleteResult:
    """Delete one deployment; returns a typed delete result."""

    response_payload = await client.delete_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
    )
    return RancherCuratedDeleteResult(
        instance=instance_name,
        plane="steve",
        resource_kind="deployment",
        resource_name=deployment_name,
        namespace=namespace,
        cluster_id=cluster_id,
        deleted=True,
        confirmation_phrase_used=confirmation_phrase_used,
        response_payload=dict(response_payload),
        suggested_next_steps=["rancher_deployments_list"],
    )


@audit_mutation(operation="deployment_delete", plane="steve")
@rate_limit_writes
async def rancher_deployment_delete(
    namespace: str,
    deployment_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one deployment after the agent echoes the required confirmation phrase."""

    expected_phrase = f"delete deployment {deployment_name} in namespace {namespace}"
    if confirmation != expected_phrase:
        raise RancherCapabilityError(
            f"Delete confirmation did not match the required phrase: {expected_phrase!r}"
        )
    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _delete_deployment(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            expected_phrase,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _delete_deployment(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            expected_phrase,
            managed_client,
        )


async def _patch_deployment_scale(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    replicas: int,
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Scale one deployment via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["replicas"] = replicas
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"spec": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
        ),
        target_path="spec",
        patch_subtree=patch_subtree,
        kind="deployment",
        action="scale",
        name=deployment_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="scale",
        kind="deployment",
        name=deployment_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="deployment_scale", plane="steve")
@rate_limit_writes
async def rancher_deployment_scale(
    namespace: str,
    deployment_name: str,
    replicas: int,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Scale one deployment via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_deployment_scale(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            replicas,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_deployment_scale(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            replicas,
            managed_client,
        )


async def _patch_deployment_set_labels(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    labels: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_labels one deployment via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["labels"] = labels
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="deployment",
        action="set_labels",
        name=deployment_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_labels",
        kind="deployment",
        name=deployment_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="deployment_set_labels", plane="steve")
@rate_limit_writes
async def rancher_deployment_set_labels(
    namespace: str,
    deployment_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_labels one deployment via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_deployment_set_labels(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            labels,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_deployment_set_labels(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            labels,
            managed_client,
        )


async def _patch_deployment_set_annotations(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    annotations: dict[str, str],
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Set_annotations one deployment via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {}
    patch_subtree["annotations"] = annotations
    if not patch_subtree:
        raise RancherCapabilityError(
            "No patch fields provided; every arg was None. Pass at least one field to update."
        )
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"metadata": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
        ),
        target_path="metadata",
        patch_subtree=patch_subtree,
        kind="deployment",
        action="set_annotations",
        name=deployment_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="set_annotations",
        kind="deployment",
        name=deployment_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="deployment_set_annotations", plane="steve")
@rate_limit_writes
async def rancher_deployment_set_annotations(
    namespace: str,
    deployment_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Set_annotations one deployment via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_deployment_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            annotations,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_deployment_set_annotations(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            annotations,
            managed_client,
        )


async def _patch_deployment_pause(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Pause one deployment via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {"paused": True}
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"spec": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
        ),
        target_path="spec",
        patch_subtree=patch_subtree,
        kind="deployment",
        action="pause",
        name=deployment_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="pause",
        kind="deployment",
        name=deployment_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="deployment_pause", plane="steve")
@rate_limit_writes
async def rancher_deployment_pause(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Pause one deployment via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_deployment_pause(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_deployment_pause(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            managed_client,
        )


async def _patch_deployment_resume(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Resume one deployment via JSON merge-patch; returns a mutation receipt."""

    patch_subtree: dict[str, object] = {"paused": False}
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"spec": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
        ),
        target_path="spec",
        patch_subtree=patch_subtree,
        kind="deployment",
        action="resume",
        name=deployment_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="resume",
        kind="deployment",
        name=deployment_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="deployment_resume", plane="steve")
@rate_limit_writes
async def rancher_deployment_resume(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Resume one deployment via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_deployment_resume(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_deployment_resume(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            managed_client,
        )


async def _patch_deployment_restart(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    deployment_name: str,
    client: ManagementDiscoveryClient,
) -> RancherMutationReceipt:
    """Restart one deployment via JSON merge-patch; returns a mutation receipt."""

    from rancher_mcp.tools.support.dynamic_values import (
        deployment_restart_target_value as _target_value_factory,
    )

    patch_subtree: dict[str, object] = _target_value_factory()
    request_payload: dict[str, object] = patch_subtree
    request_payload = {"spec": request_payload}

    before = await fetch_patch_before(
        lambda: client.get_json(
            workload_resource_path(cluster_id, namespace, "deployments", deployment_name)
        ),
        target_path="spec",
        patch_subtree=patch_subtree,
        kind="deployment",
        action="restart",
        name=deployment_name,
    )
    patch_started_at = time.monotonic()
    await client.patch_json(
        workload_resource_path(cluster_id, namespace, "deployments", deployment_name),
        payload=request_payload,
    )
    duration_ms = int((time.monotonic() - patch_started_at) * 1000)
    return RancherMutationReceipt(
        instance=instance_name,
        plane="steve",
        action="restart",
        kind="deployment",
        name=deployment_name,
        cluster_id=cluster_id,
        namespace=namespace,
        changed=dict(patch_subtree),
        before=before,
        duration_ms=duration_ms,
    )


@audit_mutation(operation="deployment_restart", plane="steve")
@rate_limit_writes
async def rancher_deployment_restart(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherMutationReceipt:
    """Restart one deployment via JSON merge-patch."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    ensure_instance_writable(instance_name, instance_config)
    if client is not None:
        return await _patch_deployment_restart(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            client,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _patch_deployment_restart(
            instance_name,
            cluster_id,
            namespace,
            deployment_name,
            managed_client,
        )


async def rancher_deployments_list_tool(
    namespace: str,
    cluster_id: str = "local",
    ready: bool | None = None,
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherDeploymentList:
    """List deployments as lightweight typed summaries — identity, state, and a per-item health rollup rather than full specs — so an agent can enumerate what exists before opening any one in detail with the matching get tool."""

    return await rancher_deployments_list(
        namespace=namespace,
        cluster_id=cluster_id,
        ready=ready,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_deployment_get_tool(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherDeploymentDetail:
    """Fetch one deployment and return its full typed detail: the conditions, diagnostics, and derived fields the list summary leaves out. Call this once a list has identified which one to inspect."""

    return await rancher_deployment_get(
        namespace=namespace,
        deployment_name=deployment_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_delete_tool(
    namespace: str,
    deployment_name: str,
    confirmation: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherCuratedDeleteResult:
    """Delete one deployment and return a typed receipt of what was removed. Destructive and irreversible — the caller must first echo the exact confirmation phrase the tool requires."""

    return await rancher_deployment_delete(
        namespace=namespace,
        deployment_name=deployment_name,
        confirmation=confirmation,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_scale_tool(
    namespace: str,
    deployment_name: str,
    replicas: int,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one deployment in place (scale) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_deployment_scale(
        namespace=namespace,
        deployment_name=deployment_name,
        replicas=replicas,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_set_labels_tool(
    namespace: str,
    deployment_name: str,
    labels: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one deployment in place (set labels) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_deployment_set_labels(
        namespace=namespace,
        deployment_name=deployment_name,
        labels=labels,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_set_annotations_tool(
    namespace: str,
    deployment_name: str,
    annotations: dict[str, str],
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one deployment in place (set annotations) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_deployment_set_annotations(
        namespace=namespace,
        deployment_name=deployment_name,
        annotations=annotations,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_pause_tool(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one deployment in place (pause) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_deployment_pause(
        namespace=namespace,
        deployment_name=deployment_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_resume_tool(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one deployment in place (resume) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_deployment_resume(
        namespace=namespace,
        deployment_name=deployment_name,
        cluster_id=cluster_id,
        instance=instance,
    )


async def rancher_deployment_restart_tool(
    namespace: str,
    deployment_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherMutationReceipt:
    """Modify one deployment in place (restart) via a JSON merge-patch and return a mutation receipt — the before and after of only the changed fields, not the whole object. A targeted write."""

    return await rancher_deployment_restart(
        namespace=namespace,
        deployment_name=deployment_name,
        cluster_id=cluster_id,
        instance=instance,
    )
