# This file is generated by scripts/codegen from
# catalog/curated_tools/configmaps.yml. Do not edit by hand.
# Regenerate with: make codegen

"""Curated Rancher config_map tools."""

from __future__ import annotations

from rancher_mcp.clients.management import ManagementDiscoveryClient, RancherManagementClient
from rancher_mcp.config import AppSettings, get_settings
from rancher_mcp.models.config_secrets import RancherConfigMapDetail, RancherConfigMapList
from rancher_mcp.services.instances import resolve_instance
from rancher_mcp.services.resources.builders_pagination import next_page_token_from_payload
from rancher_mcp.tools.config_secrets.paths import core_v1_collection_path, core_v1_resource_path
from rancher_mcp.tools.config_secrets.shared import (
    build_list_query_params,
    config_map_summary_from_payload,
    items,
)
from rancher_mcp.tools.support.values import mapping_value, string_dict


async def _fetch_config_maps_list(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    limit: int | None,
    label_selector: str | None,
    field_selector: str | None,
    client: ManagementDiscoveryClient,
    page_token: str | None = None,
) -> RancherConfigMapList:
    """Fetch and normalize config_maps through Rancher's raw Kubernetes proxy."""

    query_params = build_list_query_params(
        limit=limit,
        continue_token=page_token,
        label_selector=label_selector,
        field_selector=field_selector,
    )
    payload = await client.get_json(
        core_v1_collection_path(cluster_id, namespace, "configmaps"),
        params=query_params or None,
    )
    config_maps = [config_map_summary_from_payload(item) for item in items(payload)]
    return RancherConfigMapList(
        instance=instance_name,
        cluster_id=cluster_id,
        namespace=namespace,
        config_map_count=len(config_maps),
        next_page_token=next_page_token_from_payload(payload),
        applied_query_params=query_params,
        config_maps=config_maps,
        suggested_next_steps=[
            "rancher_config_map_get",
            "rancher_pods_list",
        ],
    )


async def rancher_config_maps_list(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherConfigMapList:
    """List config_maps in one namespace with typed summaries."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_config_maps_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            client,
            page_token,
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_config_maps_list(
            instance_name,
            cluster_id,
            namespace,
            limit,
            label_selector,
            field_selector,
            managed_client,
            page_token,
        )


async def _fetch_config_map_get(
    instance_name: str,
    cluster_id: str,
    namespace: str,
    config_map_name: str,
    client: ManagementDiscoveryClient,
) -> RancherConfigMapDetail:
    """Fetch and normalize one config_map."""

    payload = await client.get_json(
        core_v1_resource_path(cluster_id, namespace, "configmaps", config_map_name)
    )
    summary = config_map_summary_from_payload(payload)

    metadata = mapping_value(payload, "metadata") or {}
    annotations = mapping_value(metadata, "annotations") or {}
    data_dict = mapping_value(payload, "data") or {}
    binary_data_dict = mapping_value(payload, "binaryData") or {}
    detail = RancherConfigMapDetail.model_validate(payload)
    return detail.model_copy(
        update={
            "data_key_count": summary.data_key_count,
            "binary_data_key_count": summary.binary_data_key_count,
            "immutable": summary.immutable,
            "annotation_keys": sorted(string_dict(annotations)),
            "data_keys": sorted(string_dict(data_dict)),
            "binary_data_keys": sorted(string_dict(binary_data_dict)),
            "payload": dict(payload),
            "suggested_next_steps": ["rancher_config_maps_list", "rancher_pods_list"],
        }
    )


async def rancher_config_map_get(
    namespace: str,
    config_map_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
    settings: AppSettings | None = None,
    client: ManagementDiscoveryClient | None = None,
) -> RancherConfigMapDetail:
    """Fetch one config_map by namespace and name."""

    resolved_settings = settings or get_settings()
    instance_name, instance_config = resolve_instance(resolved_settings, instance)
    if client is not None:
        return await _fetch_config_map_get(
            instance_name, cluster_id, namespace, config_map_name, client
        )
    async with RancherManagementClient(instance_name, instance_config) as managed_client:
        return await _fetch_config_map_get(
            instance_name,
            cluster_id,
            namespace,
            config_map_name,
            managed_client,
        )


async def rancher_config_maps_list_tool(
    namespace: str,
    cluster_id: str = "local",
    limit: int | None = None,
    label_selector: str | None = None,
    field_selector: str | None = None,
    page_token: str | None = None,
    instance: str | None = None,
) -> RancherConfigMapList:
    """Public MCP wrapper for curated config_map list."""

    return await rancher_config_maps_list(
        namespace=namespace,
        cluster_id=cluster_id,
        limit=limit,
        label_selector=label_selector,
        field_selector=field_selector,
        page_token=page_token,
        instance=instance,
    )


async def rancher_config_map_get_tool(
    namespace: str,
    config_map_name: str,
    cluster_id: str = "local",
    instance: str | None = None,
) -> RancherConfigMapDetail:
    """Public MCP wrapper for curated config_map detail."""

    return await rancher_config_map_get(
        namespace=namespace,
        config_map_name=config_map_name,
        cluster_id=cluster_id,
        instance=instance,
    )
